### ISSUE TITLE
Tag 1.0? 

### ISSUE THREAD

**Issue by kevinburke** [ncb000gt/node.bcrypt.js#267]
Is the API for this module stable? Lots of people are using it every day in all sorts of production applications.

**Comment by defunctzombie** [comment]
Yes, it is stable.

**Comment by kevinburke** [comment]
Is the API expected to change? Why not release 1.0.0?

On Friday, January 9, 2015, Roman Shtylman <notifications@github.com> wrote:

> Yes, it is stable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncb000gt/node.bcrypt.js/issues/267#issuecomment-69444328>
> .
>


-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by defunctzombie** [comment]
It makes no difference.
