### ISSUE TITLE
IOjs v1.0.3 not able to load bcrypt module (Windows)

### ISSUE THREAD

**Issue by dvlsg** [ncb000gt/node.bcrypt.js#272]
I am unable to load Bcrypt into an IOjs module. On require('bcrypt'), an error is thrown from bindings. The bcrypt module can be loaded in with nodejs v0.10.33 without issue.

Here is a quick rundown of my specs (can provide more info, if necessary):
- Windows 7 x64
- IOjs v1.0.3 x64
- Bcrypt v0.8.1
   - Bindings v1.0.0
   - Nan v1.5.0
- Visual Studio 2012 (for gyp)

Here is the error message thrown from `require('bcrypt')`:

    D:\Code\Personal\temp\iojs\bcrypt-test\node_modules\bcrypt\node_modules\bindings\bindings.js:79
            throw e
                  ^
    Error: Module did not self-register.
        at Error (native)
        at Module.load (module.js:341:32)
        at Function.Module._load (module.js:296:12)
        at Module.require (module.js:351:17)
        at require (module.js:370:17)
        at bindings (D:\Code\Personal\temp\iojs\bcrypt-test\node_modules\bcrypt\node_modules\binding\bindings.js:74:15)
        at Object.<anonymous> (D:\Code\Personal\temp\iojs\bcrypt-test\node_modules\bcrypt\bcrypt.js:3:35)
        at Module._compile (module.js:446:26)
        at Object.Module._extensions..js (module.js:464:10)
        at Module.load (module.js:341:32)

Here is the stdout from a `node-gyp rebuild` call (note: I used the msvs_version=2012 flag to build, but I believe this output looks exactly the same as with previous versions of bcrypt, including the same warnings about possible loss of data):

    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      blowfish.cc
      bcrypt.cc
      bcrypt_node.cc
    ..\src\bcrypt.cc(232): warning C4267: '=' : conversion from 'size_t' to 'unsigned char', possible loss of data [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    d:\code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\node_modules\nan\nan_implementation_pre_12_inl.h(156): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data (..\src\bcrypt_node.cc) [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    d:\code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\node_modules\nan\nan_implementation_pre_12_inl.h(165): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data (..\src\bcrypt_node.cc) [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    d:\code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\node_modules\nan\nan_implementation_pre_12_inl.h(183): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data (..\src\bcrypt_node.cc) [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    ..\src\bcrypt_node.cc(76): warning C4244: 'argument' : conversion from 'ssize_t' to 'unsigned char', possible loss of data [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    ..\src\bcrypt_node.cc(137): warning C4244: 'argument' : conversion from 'const ssize_t' to 'unsigned char', possible loss of data [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    ..\src\bcrypt_node.cc(231): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    ..\src\bcrypt_node.cc(232): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
    C:\Users\Dave\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
              with
              [
                  T=v8::Object
              ] (..\src\bcrypt_node.cc)
         Creating library D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\Release\bcrypt_lib.lib and object D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\Release\bcrypt_lib.exp
      Generating code
      Finished generating code
      bcrypt_lib.vcxproj -> D:\Code\clubspeed\temp\passwords\iojs\node_modules\bcrypt\build\Release\\bcrypt_lib.node

**Comment by TimofeyBiryukov** [comment]
Same here, mac 10.8.5, bcrypt 0.8.0, iojs 1.0.4.

**Comment by egeozcan** [comment]
I think nan needs to be updated to the latest version to fix this but haven't tested yet.

**Comment by xhallix** [comment]
Same issue here for linux mint
Tried to reinstall bcrypt -> bindings@1.0.0 / nan@1.5.0 but did not help

**Comment by ncb000gt** [comment]
I just tried this on my mac (no windows to work with) and all is good. I'm not sure why you'd be seeing these issues. Maybe try starting fresh with bcrypt (remove node modules and rebuild from source) and see if you get the same errors?

**Comment by etiennea** [comment]
I had this issue on my mac with node v0.12.0

**Comment by AdriVanHoudt** [comment]
+1 Also have this on Windows 8.1, io.js 1.1.0 and bcrypt 0.8.x.
I tried fresh install by deleting node_modules and calling `npm install` again but same error. I'll try rebooting machine later and let you know if that fixed it.

**Comment by xhallix** [comment]
After upgrading to the new iojs release I removed the node Modules and made a fresh install.
That worked great for me, but only since I made an update to iojs

**Comment by AdriVanHoudt** [comment]
@xhallix what versions do you use? I tried rebooting and reinstalling but didn't work

**Comment by xhallix** [comment]
I updated to iojs 1.1.0 and using  "bcrypt"  : "0.8.x" in my package.json

**Comment by AdriVanHoudt** [comment]
Same here, are you using Windows?

**Comment by xhallix** [comment]
No I am running this on linux mint , sorry

**Comment by AdriVanHoudt** [comment]
Ok np that means it is probably a windows bug?

**Comment by AdriVanHoudt** [comment]
It might be solved with a newer nan version https://github.com/rvagg/nan/blob/master/CHANGELOG.md
Will test later

**Comment by AdriVanHoudt** [comment]
I think I found the problem (for my case).
When installing node and io.js side by side things start failing. The way bcrypt is made is it builds for a specific node version. 
* e.g. node 0.12.0. 
* When running `npm install` node-gyp will build for v0.12.0
* If you run your app on node v0.12.0 everything is fine
* Now you install io.js and bcrypt errors
* This is because bcrypt is not build for io.js
* you can then rebuild bcrypt and since io.js is tagged as version 1.1.0 node-gyp will automatically choose the highest version and in this case it will be io.js
* Now when you want to go back to node it doesn't work anymore because node version is 0.12.0 and is lower than io.js's version and node-gyp tries to build for version 1.1.0 instead of 0.12.0
* only solution I can think of is either using io.js or uninstalling io.js
