### ISSUE TITLE
Error in io.js

### ISSUE THREAD

**Issue by flyswatter** [ncb000gt/node.bcrypt.js#274]
I'm getting a strange error when running this module in an [io.js](https://iojs.org/en/index.html) environment.

This was solved by the module [node-expat](https://github.com/node-xmpp/node-expat/issues/107) by [updating the version of `nan` they were using](https://github.com/node-xmpp/node-expat/commit/cc6fe7df92f9ba599620075d7b7ccbdc5d81ae45), which I see you are also using.

I'll try that fix and send a PR if it works soon.

```
/my-project/node_modules/bcrypt/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at bindings (/my-project/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/my-project/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:446:26)
```

**Comment by flyswatter** [comment]
My mistake, you've already updated that module in your latest version, I just needed to update my `bcrypt`!

**Comment by lucasmciruzzi** [comment]
I have the same error with io.js v1.4.1 and bcrypt v0.8.1. I have all up to date, and running on Windows.

nan current version is 1.7.0 (you have 1.5.0), and bindings is 1.2.1 (1.0.0). So this needs and update.

**Comment by babsonmatt** [comment]
@lucasmciruzzi likewise

**Comment by flyswatter** [comment]
I'm reopening on behalf of these other commenters, but I'm not personally experiencing this problem anymore.

**Comment by defunctzombie** [comment]
Closing this. We will review a PR to updated the required dependencies.

**Comment by palamccc** [comment]
bcrypt@0.8.1 is not installing in windows 7 / iojs 1.6.0
c compiler is looking for  ".node-gyp/1.6.0/x64/node.lib"
But in file system only ".node-gyp/1.6.0/x64/iojs.lib" is available

**Comment by palamccc** [comment]
As workaround, I copied "iojs.lib" to "node.lib" and it worked.
