### ISSUE TITLE
release node 0.12 supporting version

### ISSUE THREAD

**Issue by vid** [ncb000gt/node.bcrypt.js#279]
is this planned soon? thanks!

I am seeing the error "module did not self-register."

**Comment by djthread** [comment]
Same here. Need to roll node back a version for now...

Thanks!! <3

**Comment by defunctzombie** [comment]
0.12 is supported

https://travis-ci.org/ncb000gt/node.bcrypt.js

**Comment by mhuebert** [comment]
I am also seeing the "module did not self-register" error. Any ideas where this comes from?
