### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by babsonmatt** [ncb000gt/node.bcrypt.js#281]
I receive this error while attempting to run my app via nodemon/forever/etc.

I'm running on win 7 x64 with iojs 1.5.1

Everything works fine if I run without the above tools.

**Comment by defunctzombie** [comment]
duplicate of #280

**Comment by babsonmatt** [comment]
Not sure if this is a duplicate as I'm able to use the library just fine... except when trying to run my app via nodemon/forever etc.

**Comment by defunctzombie** [comment]
That is an issue to take up with nodemon or forever. If it runs fine otherwise I would first start with whatever those libs are trying to do.

**Comment by babsonmatt** [comment]
I'll give that a go, thanks for your time
