### ISSUE TITLE
Unable to node-gyp rebuild bcrypt with npm install

### ISSUE THREAD

**Issue by dvlsg** [ncb000gt/node.bcrypt.js#282]
Starting here, although this may end up being a node-gyp issue, so feel to redirect if necessary.

I am able to build node.bcrypt.js from the master by downloading the master source code and then executing the following command:
`node-gyp rebuild --msvs_version=2013`

I am not able to build node.bcrypt using the following:
`npm install bcrypt --msvs_version=2013`

I suspect it's something silly that I'm just overlooking or some stupid typo, but it's escaping me at the moment. Any thoughts?

Here are my specs and npm-debug.log:

Windows 8.1 x64
NodeJS v0.12.0 x64
node-gyp v1.0.3
Python v2.7.3 x64
Visual Studio 2013 Community Edition, x64 (I thought community edition was the problem at first, but it seems to build okay from the master source)
npm config msvs_version set globally to 2013 (confirmed with `npm config get msvs_version` returning 2013)

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
    1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'install',
    1 verbose cli   'bcrypt',
    1 verbose cli   '--msvs_version=2013' ]
    2 info using npm@2.5.1
    3 info using node@v0.12.0
    4 verbose node symlink C:\Program Files\nodejs\\node.exe
    5 silly cache add args [ 'bcrypt', null ]
    6 verbose cache add spec bcrypt
    7 silly cache add parsed spec { raw: 'bcrypt',
    7 silly cache add   scope: null,
    7 silly cache add   name: 'bcrypt',
    7 silly cache add   rawSpec: '',
    7 silly cache add   spec: '*',
    7 silly cache add   type: 'range' }
    8 verbose addNamed bcrypt@*
    9 silly addNamed semver.valid null
    10 silly addNamed semver.validRange *
    11 silly addNameRange { name: 'bcrypt', range: '*', hasData: false }
    12 silly mapToRegistry name bcrypt
    13 silly mapToRegistry using default registry
    14 silly mapToRegistry registry https://registry.npmjs.org/
    15 silly mapToRegistry uri https://registry.npmjs.org/bcrypt
    16 verbose addNameRange registry:https://registry.npmjs.org/bcrypt not in flight; fetching
    17 verbose request uri https://registry.npmjs.org/bcrypt
    18 verbose request no auth needed
    19 info attempt registry request try #1 at 10:24:05 AM
    20 verbose request id 61e180588ee71789
    21 verbose etag "1UOWNFQWZR11F6VSYBULO8BD1"
    22 http request GET https://registry.npmjs.org/bcrypt
    23 http 304 https://registry.npmjs.org/bcrypt
    24 silly get cb [ 304,
    24 silly get   { date: 'Tue, 17 Mar 2015 17:24:04 GMT',
    24 silly get     server: 'Apache',
    24 silly get     via: '1.1 varnish',
    24 silly get     'last-modified': 'Tue, 17 Mar 2015 17:24:04 GMT',
    24 silly get     'cache-control': 'max-age=60',
    24 silly get     etag: '"1UOWNFQWZR11F6VSYBULO8BD1"',
    24 silly get     age: '52',
    24 silly get     'x-served-by': 'cache-iad2123-IAD',
    24 silly get     'x-cache': 'HIT',
    24 silly get     'x-cache-hits': '1',
    24 silly get     'x-timer': 'S1426613044.565986,VS0,VE0',
    24 silly get     vary: 'Accept',
    24 silly get     'content-length': '0',
    24 silly get     'keep-alive': 'timeout=10, max=50',
    24 silly get     connection: 'Keep-Alive' } ]
    25 verbose etag https://registry.npmjs.org/bcrypt from cache
    26 verbose get saving bcrypt to C:\Users\Dave\AppData\Roaming\npm-cache\registry.npmjs.org\bcrypt\.cache.json
    27 silly addNameRange number 2 { name: 'bcrypt', range: '*', hasData: true }
    28 silly addNameRange versions [ 'bcrypt',
    28 silly addNameRange   [ '0.1.2',
    28 silly addNameRange     '0.2.0',
    28 silly addNameRange     '0.2.1',
    28 silly addNameRange     '0.1.3',
    28 silly addNameRange     '0.2.2',
    28 silly addNameRange     '0.2.3',
    28 silly addNameRange     '0.2.4',
    28 silly addNameRange     '0.3.0',
    28 silly addNameRange     '0.3.1',
    28 silly addNameRange     '0.3.2',
    28 silly addNameRange     '0.4.0',
    28 silly addNameRange     '0.4.1',
    28 silly addNameRange     '0.5.0',
    28 silly addNameRange     '0.6.0',
    28 silly addNameRange     '0.7.0',
    28 silly addNameRange     '0.7.1',
    28 silly addNameRange     '0.7.2',
    28 silly addNameRange     '0.7.3',
    28 silly addNameRange     '0.7.4',
    28 silly addNameRange     '0.7.5',
    28 silly addNameRange     '0.7.6',
    28 silly addNameRange     '0.7.7',
    28 silly addNameRange     '0.7.8',
    28 silly addNameRange     '0.8.0',
    28 silly addNameRange     '0.8.1' ] ]
    29 verbose addNamed bcrypt@0.8.1
    30 silly addNamed semver.valid 0.8.1
    31 silly addNamed semver.validRange 0.8.1
    32 silly cache afterAdd bcrypt@0.8.1
    33 verbose afterAdd C:\Users\Dave\AppData\Roaming\npm-cache\bcrypt\0.8.1\package\package.json not in flight; writing
    34 verbose afterAdd C:\Users\Dave\AppData\Roaming\npm-cache\bcrypt\0.8.1\package\package.json written
    35 silly install resolved [ { name: 'bcrypt',
    35 silly install resolved     description: 'A bcrypt library for NodeJS.',
    35 silly install resolved     keywords:
    35 silly install resolved      [ 'bcrypt',
    35 silly install resolved        'password',
    35 silly install resolved        'auth',
    35 silly install resolved        'authentication',
    35 silly install resolved        'encryption',
    35 silly install resolved        'crypt',
    35 silly install resolved        'crypto' ],
    35 silly install resolved     main: './bcrypt',
    35 silly install resolved     version: '0.8.1',
    35 silly install resolved     author: { name: 'Nick Campbell', url: 'https://github.com/ncb000gt' },
    35 silly install resolved     engines: { node: '>= 0.6.0' },
    35 silly install resolved     repository:
    35 silly install resolved      { type: 'git',
    35 silly install resolved        url: 'https://github.com/ncb000gt/node.bcrypt.js.git' },
    35 silly install resolved     licenses: [ [Object] ],
    35 silly install resolved     bugs: { url: 'https://github.com/ncb000gt/node.bcrypt.js/issues' },
    35 silly install resolved     scripts:
    35 silly install resolved      { test: 'node-gyp configure build && nodeunit test',
    35 silly install resolved        install: 'node-gyp rebuild' },
    35 silly install resolved     dependencies: { bindings: '1.0.0', nan: '1.5.0' },
    35 silly install resolved     devDependencies: { nodeunit: '>=0.6.4' },
    35 silly install resolved     contributors:
    35 silly install resolved      [ [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object],
    35 silly install resolved        [Object] ],
    35 silly install resolved     gypfile: true,
    35 silly install resolved     gitHead: '1c76a3000c4e3a89f6e59d3f66e6d7b9da51affd',
    35 silly install resolved     homepage: 'https://github.com/ncb000gt/node.bcrypt.js',
    35 silly install resolved     _id: 'bcrypt@0.8.1',
    35 silly install resolved     _shasum: '384fa4fbc106ec87ccf8ee3d1e7e12d0ef8eeaaf',
    35 silly install resolved     _from: 'bcrypt@*',
    35 silly install resolved     _npmVersion: '2.1.12',
    35 silly install resolved     _nodeVersion: '0.10.33',
    35 silly install resolved     _npmUser: { name: 'shtylman', email: 'shtylman@gmail.com' },
    35 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
    35 silly install resolved     dist:
    35 silly install resolved      { shasum: '384fa4fbc106ec87ccf8ee3d1e7e12d0ef8eeaaf',
    35 silly install resolved        tarball: 'http://registry.npmjs.org/bcrypt/-/bcrypt-0.8.1.tgz' },
    35 silly install resolved     directories: {},
    35 silly install resolved     _resolved: 'https://registry.npmjs.org/bcrypt/-/bcrypt-0.8.1.tgz',
    35 silly install resolved     readme: 'ERROR: No README data found!' } ]
    36 info install bcrypt@0.8.1 into D:\Code\bcrypt-test
    37 info installOne bcrypt@0.8.1
    38 verbose installOne of bcrypt to D:\Code\bcrypt-test not in flight; installing
    39 verbose lock using C:\Users\Dave\AppData\Roaming\npm-cache\_locks\bcrypt-980df5c72b84377d.lock for D:\Code\bcrypt-test\node_modules\bcrypt
    40 silly install write writing bcrypt 0.8.1 to D:\Code\bcrypt-test\node_modules\bcrypt
    41 silly cache addNamed cb bcrypt@0.8.1
    42 verbose unbuild node_modules\bcrypt
    43 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt
    44 verbose tar unpack C:\Users\Dave\AppData\Roaming\npm-cache\bcrypt\0.8.1\package.tgz
    45 verbose tar unpacking to D:\Code\bcrypt-test\node_modules\bcrypt
    46 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt
    47 silly gunzTarPerm modes [ '777', '666' ]
    48 silly gunzTarPerm extractEntry package.json
    49 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
    50 silly gunzTarPerm extractEntry .npmignore
    51 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
    52 silly gunzTarPerm extractEntry README.md
    53 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
    54 silly gunzTarPerm extractEntry LICENSE
    55 silly gunzTarPerm modified mode [ 'LICENSE', 420, 438 ]
    56 silly gunzTarPerm extractEntry bcrypt.js
    57 silly gunzTarPerm modified mode [ 'bcrypt.js', 420, 438 ]
    58 silly gunzTarPerm extractEntry binding.gyp
    59 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
    60 silly gunzTarPerm extractEntry .travis.yml
    61 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
    62 silly gunzTarPerm extractEntry CHANGELOG.md
    63 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 420, 438 ]
    64 silly gunzTarPerm extractEntry examples/async_compare.js
    65 silly gunzTarPerm modified mode [ 'examples/async_compare.js', 420, 438 ]
    66 silly gunzTarPerm extractEntry examples/forever_gen_salt.js
    67 silly gunzTarPerm modified mode [ 'examples/forever_gen_salt.js', 420, 438 ]
    68 silly gunzTarPerm extractEntry test/async.js
    69 silly gunzTarPerm modified mode [ 'test/async.js', 420, 438 ]
    70 silly gunzTarPerm extractEntry test/repetitions.js
    71 silly gunzTarPerm modified mode [ 'test/repetitions.js', 420, 438 ]
    72 silly gunzTarPerm extractEntry test/sync.js
    73 silly gunzTarPerm modified mode [ 'test/sync.js', 420, 438 ]
    74 silly gunzTarPerm extractEntry Makefile
    75 silly gunzTarPerm modified mode [ 'Makefile', 420, 438 ]
    76 silly gunzTarPerm extractEntry src/bcrypt.cc
    77 silly gunzTarPerm modified mode [ 'src/bcrypt.cc', 420, 438 ]
    78 silly gunzTarPerm extractEntry src/bcrypt_node.cc
    79 silly gunzTarPerm modified mode [ 'src/bcrypt_node.cc', 420, 438 ]
    80 silly gunzTarPerm extractEntry src/blowfish.cc
    81 silly gunzTarPerm modified mode [ 'src/blowfish.cc', 420, 438 ]
    82 silly gunzTarPerm extractEntry src/node_blf.h
    83 silly gunzTarPerm modified mode [ 'src/node_blf.h', 420, 438 ]
    84 silly gunzTarPerm extractEntry werker.yml
    85 silly gunzTarPerm modified mode [ 'werker.yml', 420, 438 ]
    86 info preinstall bcrypt@0.8.1
    87 silly prepareForInstallMany adding bindings@1.0.0 from bcrypt dependencies
    88 silly prepareForInstallMany adding nan@1.5.0 from bcrypt dependencies
    89 silly cache add args [ 'bindings@1.0.0', null ]
    90 verbose cache add spec bindings@1.0.0
    91 silly cache add args [ 'nan@1.5.0', null ]
    92 verbose cache add spec nan@1.5.0
    93 silly cache add parsed spec { raw: 'bindings@1.0.0',
    93 silly cache add   scope: null,
    93 silly cache add   name: 'bindings',
    93 silly cache add   rawSpec: '1.0.0',
    93 silly cache add   spec: '1.0.0',
    93 silly cache add   type: 'version' }
    94 verbose addNamed bindings@1.0.0
    95 silly addNamed semver.valid 1.0.0
    96 silly addNamed semver.validRange 1.0.0
    97 silly mapToRegistry name bindings
    98 silly mapToRegistry using default registry
    99 silly mapToRegistry registry https://registry.npmjs.org/
    100 silly mapToRegistry uri https://registry.npmjs.org/bindings
    101 verbose addNameVersion registry:https://registry.npmjs.org/bindings not in flight; fetching
    102 silly cache add parsed spec { raw: 'nan@1.5.0',
    102 silly cache add   scope: null,
    102 silly cache add   name: 'nan',
    102 silly cache add   rawSpec: '1.5.0',
    102 silly cache add   spec: '1.5.0',
    102 silly cache add   type: 'version' }
    103 verbose addNamed nan@1.5.0
    104 silly addNamed semver.valid 1.5.0
    105 silly addNamed semver.validRange 1.5.0
    106 silly mapToRegistry name nan
    107 silly mapToRegistry using default registry
    108 silly mapToRegistry registry https://registry.npmjs.org/
    109 silly mapToRegistry uri https://registry.npmjs.org/nan
    110 verbose addNameVersion registry:https://registry.npmjs.org/nan not in flight; fetching
    111 verbose request uri https://registry.npmjs.org/bindings
    112 verbose request no auth needed
    113 info attempt registry request try #1 at 10:24:05 AM
    114 verbose etag "5997G8NY1OJEMZ1HNHL7VBX5J"
    115 http request GET https://registry.npmjs.org/bindings
    116 verbose request uri https://registry.npmjs.org/nan
    117 verbose request no auth needed
    118 info attempt registry request try #1 at 10:24:05 AM
    119 verbose etag "53INR1O88FGBCSW2EGGM70X6N"
    120 http request GET https://registry.npmjs.org/nan
    121 http 304 https://registry.npmjs.org/nan
    122 silly get cb [ 304,
    122 silly get   { date: 'Tue, 17 Mar 2015 17:24:05 GMT',
    122 silly get     server: 'Apache',
    122 silly get     via: '1.1 varnish',
    122 silly get     'last-modified': 'Tue, 17 Mar 2015 17:24:05 GMT',
    122 silly get     'cache-control': 'max-age=60',
    122 silly get     etag: '"53INR1O88FGBCSW2EGGM70X6N"',
    122 silly get     age: '31',
    122 silly get     'x-served-by': 'cache-iad2140-IAD',
    122 silly get     'x-cache': 'HIT',
    122 silly get     'x-cache-hits': '1',
    122 silly get     'x-timer': 'S1426613045.030802,VS0,VE0',
    122 silly get     vary: 'Accept',
    122 silly get     'content-length': '0',
    122 silly get     'keep-alive': 'timeout=10, max=50',
    122 silly get     connection: 'Keep-Alive' } ]
    123 verbose etag https://registry.npmjs.org/nan from cache
    124 verbose get saving nan to C:\Users\Dave\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
    125 http 304 https://registry.npmjs.org/bindings
    126 silly get cb [ 304,
    126 silly get   { date: 'Tue, 17 Mar 2015 17:24:05 GMT',
    126 silly get     server: 'Apache',
    126 silly get     via: '1.1 varnish',
    126 silly get     'last-modified': 'Tue, 17 Mar 2015 17:24:05 GMT',
    126 silly get     'cache-control': 'max-age=60',
    126 silly get     etag: '"5997G8NY1OJEMZ1HNHL7VBX5J"',
    126 silly get     age: '48',
    126 silly get     'x-served-by': 'cache-iad2124-IAD',
    126 silly get     'x-cache': 'HIT',
    126 silly get     'x-cache-hits': '1',
    126 silly get     'x-timer': 'S1426613045.037975,VS0,VE0',
    126 silly get     vary: 'Accept',
    126 silly get     'content-length': '0',
    126 silly get     'keep-alive': 'timeout=10, max=50',
    126 silly get     connection: 'Keep-Alive' } ]
    127 verbose etag https://registry.npmjs.org/bindings from cache
    128 verbose get saving bindings to C:\Users\Dave\AppData\Roaming\npm-cache\registry.npmjs.org\bindings\.cache.json
    129 silly cache afterAdd bindings@1.0.0
    130 verbose afterAdd C:\Users\Dave\AppData\Roaming\npm-cache\bindings\1.0.0\package\package.json not in flight; writing
    131 silly cache afterAdd nan@1.5.0
    132 verbose afterAdd C:\Users\Dave\AppData\Roaming\npm-cache\nan\1.5.0\package\package.json not in flight; writing
    133 verbose afterAdd C:\Users\Dave\AppData\Roaming\npm-cache\bindings\1.0.0\package\package.json written
    134 verbose afterAdd C:\Users\Dave\AppData\Roaming\npm-cache\nan\1.5.0\package\package.json written
    135 silly install resolved [ { name: 'bindings',
    135 silly install resolved     description: 'Helper module for loading your native module\'s .node file',
    135 silly install resolved     keywords: [ 'native', 'addon', 'bindings', 'gyp', 'waf', 'c', 'c++' ],
    135 silly install resolved     version: '1.0.0',
    135 silly install resolved     author:
    135 silly install resolved      { name: 'Nathan Rajlich',
    135 silly install resolved        email: 'nathan@tootallnate.net',
    135 silly install resolved        url: 'http://tootallnate.net' },
    135 silly install resolved     repository:
    135 silly install resolved      { type: 'git',
    135 silly install resolved        url: 'git://github.com/TooTallNate/node-bindings.git' },
    135 silly install resolved     main: './bindings.js',
    135 silly install resolved     _id: 'bindings@1.0.0',
    135 silly install resolved     dist:
    135 silly install resolved      { shasum: 'c3ccde60e9de6807c6f1aa4ef4843af29191c828',
    135 silly install resolved        tarball: 'http://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz' },
    135 silly install resolved     maintainers: [ [Object], [Object] ],
    135 silly install resolved     directories: {},
    135 silly install resolved     _shasum: 'c3ccde60e9de6807c6f1aa4ef4843af29191c828',
    135 silly install resolved     _resolved: 'https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz',
    135 silly install resolved     _from: 'bindings@1.0.0',
    135 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-bindings/issues' },
    135 silly install resolved     readme: 'ERROR: No README data found!',
    135 silly install resolved     homepage: 'https://github.com/TooTallNate/node-bindings' },
    135 silly install resolved   { name: 'nan',
    135 silly install resolved     version: '1.5.0',
    135 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
    135 silly install resolved     main: 'include_dirs.js',
    135 silly install resolved     repository: { type: 'git', url: 'git://github.com/rvagg/nan.git' },
    135 silly install resolved     scripts:
    135 silly install resolved      { test: 'tap --gc test/js/*-test.js',
    135 silly install resolved        'rebuild-tests': 'node-gyp rebuild --directory test' },
    135 silly install resolved     contributors:
    135 silly install resolved      [ [Object],
    135 silly install resolved        [Object],
    135 silly install resolved        [Object],
    135 silly install resolved        [Object],
    135 silly install resolved        [Object],
    135 silly install resolved        [Object],
    135 silly install resolved        [Object] ],
    135 silly install resolved     devDependencies:
    135 silly install resolved      { bindings: '~1.2.1',
    135 silly install resolved        'node-gyp': '~1.0.2',
    135 silly install resolved        tap: '~0.4.13',
    135 silly install resolved        xtend: '~4.0.0' },
    135 silly install resolved     license: 'MIT',
    135 silly install resolved     gitHead: '6fea75acc8f78124756ff4d8e536b6196aca3d37',
    135 silly install resolved     bugs: { url: 'https://github.com/rvagg/nan/issues' },
    135 silly install resolved     homepage: 'https://github.com/rvagg/nan',
    135 silly install resolved     _id: 'nan@1.5.0',
    135 silly install resolved     _shasum: '2b3c05bc361f52e50aea2c49077783aa67c5b7fb',
    135 silly install resolved     _from: 'nan@1.5.0',
    135 silly install resolved     _npmVersion: '2.1.18',
    135 silly install resolved     _nodeVersion: '0.11.14',
    135 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
    135 silly install resolved     maintainers: [ [Object], [Object] ],
    135 silly install resolved     dist:
    135 silly install resolved      { shasum: '2b3c05bc361f52e50aea2c49077783aa67c5b7fb',
    135 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.5.0.tgz' },
    135 silly install resolved     directories: {},
    135 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.5.0.tgz',
    135 silly install resolved     readme: 'ERROR: No README data found!' } ]
    136 info install bindings@1.0.0 into D:\Code\bcrypt-test\node_modules\bcrypt
    137 info install nan@1.5.0 into D:\Code\bcrypt-test\node_modules\bcrypt
    138 info installOne bindings@1.0.0
    139 verbose installOne of bindings to D:\Code\bcrypt-test\node_modules\bcrypt not in flight; installing
    140 info installOne nan@1.5.0
    141 verbose installOne of nan to D:\Code\bcrypt-test\node_modules\bcrypt not in flight; installing
    142 verbose lock using C:\Users\Dave\AppData\Roaming\npm-cache\_locks\bindings-9d5be3be0b599a9d.lock for D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    143 silly install write writing bindings 1.0.0 to D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    144 silly cache addNamed cb bindings@1.0.0
    145 verbose unbuild node_modules\bcrypt\node_modules\bindings
    146 verbose lock using C:\Users\Dave\AppData\Roaming\npm-cache\_locks\nan-58b228866a985e4f.lock for D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    147 silly install write writing nan 1.5.0 to D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    148 silly cache addNamed cb nan@1.5.0
    149 verbose unbuild node_modules\bcrypt\node_modules\nan
    150 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    151 verbose tar unpack C:\Users\Dave\AppData\Roaming\npm-cache\bindings\1.0.0\package.tgz
    152 verbose tar unpacking to D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    153 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    154 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    155 silly gunzTarPerm modes [ '777', '666' ]
    156 verbose tar unpack C:\Users\Dave\AppData\Roaming\npm-cache\nan\1.5.0\package.tgz
    157 verbose tar unpacking to D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    158 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    159 silly gunzTarPerm modes [ '777', '666' ]
    160 silly gunzTarPerm extractEntry package.json
    161 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
    162 silly gunzTarPerm extractEntry package.json
    163 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
    164 silly gunzTarPerm extractEntry README.md
    165 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
    166 silly gunzTarPerm extractEntry bindings.js
    167 silly gunzTarPerm modified mode [ 'bindings.js', 420, 438 ]
    168 silly gunzTarPerm extractEntry README.md
    169 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
    170 silly gunzTarPerm extractEntry include_dirs.js
    171 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 438 ]
    172 silly gunzTarPerm extractEntry LICENSE.md
    173 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
    174 silly gunzTarPerm extractEntry .dntrc
    175 silly gunzTarPerm modified mode [ '.dntrc', 436, 438 ]
    176 silly gunzTarPerm extractEntry appveyor.yml
    177 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 438 ]
    178 silly gunzTarPerm extractEntry build/config.gypi
    179 silly gunzTarPerm modified mode [ 'build/config.gypi', 436, 438 ]
    180 info preinstall bindings@1.0.0
    181 silly gunzTarPerm extractEntry nan.h
    182 silly gunzTarPerm modified mode [ 'nan.h', 436, 438 ]
    183 silly install resolved []
    184 verbose about to build D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    185 info build D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    186 verbose linkStuff [ false,
    186 verbose linkStuff   false,
    186 verbose linkStuff   false,
    186 verbose linkStuff   'D:\\Code\\bcrypt-test\\node_modules\\bcrypt\\node_modules' ]
    187 info linkStuff bindings@1.0.0
    188 verbose linkBins bindings@1.0.0
    189 verbose linkMans bindings@1.0.0
    190 verbose rebuildBundles bindings@1.0.0
    191 info install bindings@1.0.0
    192 info postinstall bindings@1.0.0
    193 verbose unlock done using C:\Users\Dave\AppData\Roaming\npm-cache\_locks\bindings-9d5be3be0b599a9d.lock for D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\bindings
    194 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
    195 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 438 ]
    196 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
    197 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 438 ]
    198 silly gunzTarPerm extractEntry nan_new.h
    199 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 438 ]
    200 silly gunzTarPerm extractEntry CHANGELOG.md
    201 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 438 ]
    202 info preinstall nan@1.5.0
    203 silly install resolved []
    204 verbose about to build D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    205 info build D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    206 verbose linkStuff [ false,
    206 verbose linkStuff   false,
    206 verbose linkStuff   false,
    206 verbose linkStuff   'D:\\Code\\bcrypt-test\\node_modules\\bcrypt\\node_modules' ]
    207 info linkStuff nan@1.5.0
    208 verbose linkBins nan@1.5.0
    209 verbose linkMans nan@1.5.0
    210 verbose rebuildBundles nan@1.5.0
    211 info install nan@1.5.0
    212 info postinstall nan@1.5.0
    213 verbose unlock done using C:\Users\Dave\AppData\Roaming\npm-cache\_locks\nan-58b228866a985e4f.lock for D:\Code\bcrypt-test\node_modules\bcrypt\node_modules\nan
    214 verbose about to build D:\Code\bcrypt-test\node_modules\bcrypt
    215 info build D:\Code\bcrypt-test\node_modules\bcrypt
    216 verbose linkStuff [ false, false, false, 'D:\\Code\\bcrypt-test\\node_modules' ]
    217 info linkStuff bcrypt@0.8.1
    218 verbose linkBins bcrypt@0.8.1
    219 verbose linkMans bcrypt@0.8.1
    220 verbose rebuildBundles bcrypt@0.8.1
    221 verbose rebuildBundles [ 'bindings', 'nan' ]
    222 info install bcrypt@0.8.1
    223 verbose unsafe-perm in lifecycle true
    224 info bcrypt@0.8.1 Failed to exec install script
    225 verbose unlock done using C:\Users\Dave\AppData\Roaming\npm-cache\_locks\bcrypt-980df5c72b84377d.lock for D:\Code\bcrypt-test\node_modules\bcrypt
    226 verbose stack Error: bcrypt@0.8.1 install: `node-gyp rebuild`
    226 verbose stack Exit status 1
    226 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
    226 verbose stack     at EventEmitter.emit (events.js:110:17)
    226 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
    226 verbose stack     at ChildProcess.emit (events.js:110:17)
    226 verbose stack     at maybeClose (child_process.js:1008:16)
    226 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
    227 verbose pkgid bcrypt@0.8.1
    228 verbose cwd D:\Code\bcrypt-test
    229 error Windows_NT 6.3.9600
    230 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--msvs_version=2013"
    231 error node v0.12.0
    232 error npm  v2.5.1
    233 error code ELIFECYCLE
    234 error bcrypt@0.8.1 install: `node-gyp rebuild`
    234 error Exit status 1
    235 error Failed at the bcrypt@0.8.1 install script 'node-gyp rebuild'.
    235 error This is most likely a problem with the bcrypt package,
    235 error not with npm itself.
    235 error Tell the author that this fails on your system:
    235 error     node-gyp rebuild
    235 error You can get their info via:
    235 error     npm owner ls bcrypt
    235 error There is likely additional logging output above.
    236 verbose exit [ 1, true ]
    237 verbose unbuild node_modules\bcrypt
    238 info preuninstall bcrypt@0.8.1
    239 info uninstall bcrypt@0.8.1
    240 verbose unbuild rmStuff bcrypt@0.8.1 from D:\Code\bcrypt-test\node_modules
    241 info postuninstall bcrypt@0.8.1
    242 verbose gentlyRm vacuuming D:\Code\bcrypt-test\node_modules\bcrypt
    243 silly gentlyRm purging D:\Code\bcrypt-test\node_modules\bcrypt
    244 silly gentlyRm removing D:\Code\bcrypt-test\node_modules
    245 silly gentlyRm finished vacuuming up to D:\Code\bcrypt-test

**Comment by davepile** [comment]
This is really a note for anyone else that comes here with a similar problem. I had previously installed bcrypt without issue. I have always had vs2012 premium installed (as well as some sort of cripled version of vs2010) but after upgrading node to 0.12 and probably getting some windows updates along the way i could not install bcrypt. I got this error message-

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform
Toolset = 'v100') cannot be found. To build using the v100 build tools, either
click the Project menu or right-click the solution, and then select "Update VC+
+ Projects...". Install Visual Studio 2010 to build using the Visual Studio 201
0 build tools. [C:\work\projects\web\CoffeeDesk\server\node_modules\bcrypt\buil
d\bcrypt_lib.vcxproj]

Using the command- `npm install bcrypt --msvs_version=2012` worked. (Thanks dvlsg)

**Comment by dvlsg** [comment]
Glad it worked for you! I'm still having issues, though.

I originally suspected that the community edition of Visual Studio may be missing some critical files, but I can confirm I have the MSBuild files at `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120` (V120 is Visual Studio 2013, I believe), and the fact that I can node-gyp rebuild from the bcrypt source files using --msvs_version=2013 seems to disprove my original suspicion. Still stumped.

**Comment by davepile** [comment]
Well one thing I did before hand was to update the internal version of node-gyp. I read somewhere if you install node-gyp globally it does not update node's internal bundled version which (i think it said) is used in installs. If you are running it from the command line you are possibly running the global install copy, not the internal version, which could be why it is working (only wild guesses here). It might be worth a try. 

To update the internal copy navigate to C:\Program Files\nodejs\node_modules\node-gyp and run `$ npm install node-gyp@latest`  (heres the reference I read https://github.com/TooTallNate/node-gyp/wiki/Updating-npm's-bundled-node-gyp)

**Comment by davepile** [comment]
Oh and one other thing I noticed. When I installed to a new project, installation worked straight away (using the --msvs_version=2012), but when I removed and then re installed to an existing project, I got an error. Removing the reference to bcrypt in package.json (which included an older version number) made it install.
