### ISSUE TITLE
Package Installation failed

### ISSUE THREAD

**Issue by kishankachchhi** [ncb000gt/node.bcrypt.js#283]
G:\work_dir\easeindex\easeindex>npm install bcrypt@0.8.1 -g
/
> bcrypt@0.8.1 install G:\work_dir\easeindex\easeindex\node_modules\bcrypt
> node-gyp rebuild

G:\work_dir\easeindex\easeindex\node_modules\bcrypt>if not defined npm_config_node_gyp (no
de "G:\work_dir\easeindex\easeindex\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: spawn c:/Python2.7/python ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "G:\\work_dir\\easeindex\\easeindex\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\work_dir\easeindex\easeindex\node_modules\bcrypt
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "G:\\work_dir\\easeindex\\easeindex\\node_modules\\npm\\bin\\npm-cli.
js" "install" "bcrypt@0.8.1" "-g"
npm ERR! node v0.11.16
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\work_dir\easeindex\easeindex\npm-debug.log

dependencies installed: 
---------------------------------------
User@pc> node -v
v0.11.16
User@pc> npm -v
2.7.1
User@pc> python -V
Python 2.7
User@pc> node-gyp -v
v1.0.2

**Comment by ncb000gt** [comment]
Take a look at: https://github.com/TooTallNate/node-gyp/issues/277
