### ISSUE TITLE
How to compare with a specific salt?

### ISSUE THREAD

**Issue by rkmax** [ncb000gt/node.bcrypt.js#284]
Right now when i got to store in my database the password I do

```js
var salt = bcrypt.getSaltSync(10);
var hash = bcrypt.hashSync('plain-pass', salt);
```

and when I go to compare the pass on login I do

```js
bcrypt.compare('plain-pass', hash).then(function(err, valid) { ... })
```

all works fine but now i moved my database to a now machine

i want compare using the salt from the previous machine

i know i can get the salt doing

```js
var salt = bcrypt.getSaltSync(10);
```

but how to used in the .compare funcion?

example

```js
bcrypt.compare('plain-pass', hash, 'previous-salt').then(function(err, valid) { ... })
```

**Comment by ncb000gt** [comment]
You use it the same way. The salt is part of the full hash in bcrypt. You shouldn't need to worry about it. So, just use the compare as you did before.

**Comment by rkmax** [comment]
@ncb000gt when i move the database to other machine all password always are wrong

**Comment by ncb000gt** [comment]
Did you rehash everything when you moved the data? Did you verify that there was nothing truncated in the move?

```javascript
> var salt = bcrypt.genSaltSync();
> var hash = bcrypt.hashSync('plain-pass', salt);
> salt
'$2a$10$YgL62UUkAnJDHw01Gtj6C.'
> hash
'$2a$10$YgL62UUkAnJDHw01Gtj6C.HaRSUXPz9eo3cDgoqeROMpRg0S1V43e'
> bcrypt.compareSync('plain-pass', hash);
true
```

If you take the hash that I've just provided and run compare against it on your machine, it should result in true.

**Comment by rkmax** [comment]
I do not know how to rehash, because passwords are unknown and are quite

**Comment by ncb000gt** [comment]
I wasn't recommending you rehash. I was suggesting that would have been a
problem.

**Comment by rkmax** [comment]
@ncb000gt What solution do you recommend?

**Comment by ncb000gt** [comment]
If you have your old db, compare the old hashes to the new. See if there
are any differences there.

- Nick Campbell

**Comment by rkmax** [comment]
@ncb000gt
