### ISSUE TITLE
Worker will die w/ malloc error when using package with out of date bcrypt

### ISSUE THREAD

**Issue by James1x0** [ncb000gt/node.bcrypt.js#288]
Say you had a plugin with an outdated package of bcrypt `0.8.0` and your main repo has `0.8.2`, it will fail when using the compare function. Not passing the error to the callback, but throwing. Less than ideal...
```
 - 5 - Node.js(78778,0x7fff7d50b300) malloc: *** error for object 0x10440d430: pointer being freed was not allocated
```
```javascript
bcp.compare(password, passwordHash, function () {});
```

**Comment by defunctzombie** [comment]
Can you provide a repo that we can easily checkout and run to reproduce this error? Please also include the nodejs version being used.

**Comment by James1x0** [comment]
Will do when I get a chance. Thanks for the reply.
