### ISSUE TITLE
What is the maximum rounds for getSaltSync ? 

### ISSUE THREAD

**Issue by pihomeserver** [ncb000gt/node.bcrypt.js#290]
Hello,

If i try 
```salt = bcrypt.genSaltSync(100);```
I get an error message when calling hashSync
```
Password : test
Salt : $2a$31$BqA3XcBGRAfgqNdBwd9bwu
Error: Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue
```

**Comment by pihomeserver** [comment]
Ok my fault, missed the Rounds bloc in the documentation. I will not go over the 31 example ;-)

**Comment by CheyenneForbes** [comment]
will it ever support more than 31?
