### ISSUE TITLE
Can't build / can't install bcrypt on Windows

### ISSUE THREAD

**Issue by DilipK01** [ncb000gt/node.bcrypt.js#294]
I'm struggling with this issue for last several days. :-( 
On my Win7 (64-bit) laptop with VS-2013 when I do: "npm install bcrypt", I get a bunch of errors as shown below. I have installed all the dependences like, openSSL, Python, Ruby, etc. In fact, everything  was working fine before. Some time ago, I updated Node and just to make sure that everything is in sync, I ran "npm install" command and now bcrypt doesn't build.

Finally, I copied the "bcrypt" folder from the production server, but my application doesn't run and so I tried again "npm update bcrypt"; but it doesn't budge. Same set of errors!!!

I have node v0.12.0 and npm v2.5.1
----------------- log file ------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bcrypt' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'bcrypt@~0.7.7', null ]
6 verbose cache add spec bcrypt@~0.7.7
7 silly cache add parsed spec { raw: 'bcrypt@~0.7.7',
7 silly cache add   scope: null,
7 silly cache add   name: 'bcrypt',
7 silly cache add   rawSpec: '~0.7.7',
7 silly cache add   spec: '>=0.7.7 <0.8.0',
7 silly cache add   type: 'range' }
8 verbose addNamed bcrypt@>=0.7.7 <0.8.0
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange >=0.7.7 <0.8.0
11 silly addNameRange { name: 'bcrypt', range: '>=0.7.7 <0.8.0', hasData: false }
12 silly mapToRegistry name bcrypt
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bcrypt
16 verbose addNameRange registry:https://registry.npmjs.org/bcrypt not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bcrypt
18 verbose request no auth needed
19 info attempt registry request try #1 at 5:50:26 PM
20 verbose request id bd4598f85102230a
21 verbose etag "A0SOBD73FZU6CC7WRJ331YCLJ"
22 http request GET https://registry.npmjs.org/bcrypt
23 http 304 https://registry.npmjs.org/bcrypt
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 13 Apr 2015 22:50:27 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Mon, 13 Apr 2015 22:50:27 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"A0SOBD73FZU6CC7WRJ331YCLJ"',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-lax1423-LAX',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1428965427.035166,VS0,VE77',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/bcrypt from cache
26 verbose get saving bcrypt to C:\Users\kumardi\AppData\Roaming\npm-cache\registry.npmjs.org\bcrypt\.cache.json
27 silly addNameRange number 2 { name: 'bcrypt', range: '>=0.7.7 <0.8.0', hasData: true }
28 silly addNameRange versions [ 'bcrypt',
28 silly addNameRange   [ '0.1.2',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.2.3',
28 silly addNameRange     '0.2.4',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1',
28 silly addNameRange     '0.7.2',
28 silly addNameRange     '0.7.3',
28 silly addNameRange     '0.7.4',
28 silly addNameRange     '0.7.5',
28 silly addNameRange     '0.7.6',
28 silly addNameRange     '0.7.7',
28 silly addNameRange     '0.7.8',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2' ] ]
29 verbose addNamed bcrypt@0.7.8
30 silly addNamed semver.valid 0.7.8
31 silly addNamed semver.validRange 0.7.8
32 silly cache afterAdd bcrypt@0.7.8
33 verbose afterAdd C:\Users\kumardi\AppData\Roaming\npm-cache\bcrypt\0.7.8\package\package.json not in flight; writing
34 verbose afterAdd C:\Users\kumardi\AppData\Roaming\npm-cache\bcrypt\0.7.8\package\package.json written
35 silly install resolved [ { name: 'bcrypt',
35 silly install resolved     description: 'A bcrypt library for NodeJS.',
35 silly install resolved     keywords:
35 silly install resolved      [ 'bcrypt',
35 silly install resolved        'password',
35 silly install resolved        'auth',
35 silly install resolved        'authentication',
35 silly install resolved        'encryption',
35 silly install resolved        'crypt',
35 silly install resolved        'crypto' ],
35 silly install resolved     main: './bcrypt',
35 silly install resolved     version: '0.7.8',
35 silly install resolved     author: { name: 'Nick Campbell', url: 'https://github.com/ncb000gt' },
35 silly install resolved     engines: { node: '>= 0.6.0' },
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'https://github.com/ncb000gt/node.bcrypt.js.git' },
35 silly install resolved     licenses: [ [Object] ],
35 silly install resolved     bugs: { url: 'https://github.com/ncb000gt/node.bcrypt.js/issues' },
35 silly install resolved     scripts:
35 silly install resolved      { test: 'node-gyp configure build && nodeunit test',
35 silly install resolved        install: 'node-gyp rebuild' },
35 silly install resolved     dependencies: { bindings: '1.0.0' },
35 silly install resolved     devDependencies: { nodeunit: '>=0.6.4' },
35 silly install resolved     contributors:
35 silly install resolved      [ [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object],
35 silly install resolved        [Object] ],
35 silly install resolved     gypfile: true,
35 silly install resolved     homepage: 'https://github.com/ncb000gt/node.bcrypt.js',
35 silly install resolved     _id: 'bcrypt@0.7.8',
35 silly install resolved     dist:
35 silly install resolved      { shasum: '42c99aac202918e947b5bd086110184f62745e3e',
35 silly install resolved        tarball: 'http://registry.npmjs.org/bcrypt/-/bcrypt-0.7.8.tgz' },
35 silly install resolved     _from: 'bcrypt@>=0.7.7 <0.8.0',
35 silly install resolved     _npmVersion: '1.4.6',
35 silly install resolved     _npmUser: { name: 'shtylman', email: 'shtylman@gmail.com' },
35 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
35 silly install resolved     directories: {},
35 silly install resolved     _shasum: '42c99aac202918e947b5bd086110184f62745e3e',
35 silly install resolved     _resolved: 'https://registry.npmjs.org/bcrypt/-/bcrypt-0.7.8.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install bcrypt@0.7.8 into C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel
37 info installOne bcrypt@0.7.8
38 verbose installOne of bcrypt to C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel not in flight; installing
39 verbose lock using C:\Users\kumardi\AppData\Roaming\npm-cache\_locks\bcrypt-e5466765c32f258e.lock for C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
40 silly install write writing bcrypt 0.7.8 to C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
41 silly cache addNamed cb bcrypt@0.7.8
42 verbose unbuild node_modules\bcrypt
43 info preuninstall bcrypt@0.7.8
44 info uninstall bcrypt@0.7.8
45 verbose unbuild rmStuff bcrypt@0.7.8 from C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules
46 info postuninstall bcrypt@0.7.8
47 verbose gentlyRm vacuuming C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
48 silly gentlyRm purging C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
49 silly gentlyRm quitting because other entries in C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules
50 verbose tar unpack C:\Users\kumardi\AppData\Roaming\npm-cache\bcrypt\0.7.8\package.tgz
51 verbose tar unpacking to C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
52 verbose gentlyRm vacuuming C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
53 silly gunzTarPerm modes [ '777', '666' ]
54 silly gunzTarPerm extractEntry package.json
55 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
56 silly gunzTarPerm extractEntry .npmignore
57 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
58 silly gunzTarPerm extractEntry README.md
59 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
60 silly gunzTarPerm extractEntry LICENSE
61 silly gunzTarPerm modified mode [ 'LICENSE', 420, 438 ]
62 silly gunzTarPerm extractEntry bcrypt.js
63 silly gunzTarPerm modified mode [ 'bcrypt.js', 420, 438 ]
64 silly gunzTarPerm extractEntry Makefile
65 silly gunzTarPerm modified mode [ 'Makefile', 420, 438 ]
66 silly gunzTarPerm extractEntry .travis.yml
67 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
68 silly gunzTarPerm extractEntry binding.gyp
69 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
70 silly gunzTarPerm extractEntry examples/async_compare.js
71 silly gunzTarPerm modified mode [ 'examples/async_compare.js', 420, 438 ]
72 silly gunzTarPerm extractEntry examples/forever_gen_salt.js
73 silly gunzTarPerm modified mode [ 'examples/forever_gen_salt.js', 420, 438 ]
74 silly gunzTarPerm extractEntry CHANGELOG
75 silly gunzTarPerm modified mode [ 'CHANGELOG', 420, 438 ]
76 silly gunzTarPerm extractEntry src/bcrypt.cc
77 silly gunzTarPerm modified mode [ 'src/bcrypt.cc', 420, 438 ]
78 silly gunzTarPerm extractEntry src/bcrypt_node.cc
79 silly gunzTarPerm modified mode [ 'src/bcrypt_node.cc', 420, 438 ]
80 silly gunzTarPerm extractEntry src/blowfish.cc
81 silly gunzTarPerm modified mode [ 'src/blowfish.cc', 420, 438 ]
82 silly gunzTarPerm extractEntry src/node_blf.h
83 silly gunzTarPerm modified mode [ 'src/node_blf.h', 420, 438 ]
84 silly gunzTarPerm extractEntry test/async.js
85 silly gunzTarPerm modified mode [ 'test/async.js', 420, 438 ]
86 silly gunzTarPerm extractEntry test/repetitions.js
87 silly gunzTarPerm modified mode [ 'test/repetitions.js', 420, 438 ]
88 silly gunzTarPerm extractEntry test/sync.js
89 silly gunzTarPerm modified mode [ 'test/sync.js', 420, 438 ]
90 info preinstall bcrypt@0.7.8
91 silly prepareForInstallMany adding bindings@1.0.0 from bcrypt dependencies
92 silly cache add args [ 'bindings@1.0.0', null ]
93 verbose cache add spec bindings@1.0.0
94 silly cache add parsed spec { raw: 'bindings@1.0.0',
94 silly cache add   scope: null,
94 silly cache add   name: 'bindings',
94 silly cache add   rawSpec: '1.0.0',
94 silly cache add   spec: '1.0.0',
94 silly cache add   type: 'version' }
95 verbose addNamed bindings@1.0.0
96 silly addNamed semver.valid 1.0.0
97 silly addNamed semver.validRange 1.0.0
98 silly mapToRegistry name bindings
99 silly mapToRegistry using default registry
100 silly mapToRegistry registry https://registry.npmjs.org/
101 silly mapToRegistry uri https://registry.npmjs.org/bindings
102 verbose addNameVersion registry:https://registry.npmjs.org/bindings not in flight; fetching
103 verbose request uri https://registry.npmjs.org/bindings
104 verbose request no auth needed
105 info attempt registry request try #1 at 5:50:27 PM
106 verbose etag "5997G8NY1OJEMZ1HNHL7VBX5J"
107 http request GET https://registry.npmjs.org/bindings
108 http 304 https://registry.npmjs.org/bindings
109 silly get cb [ 304,
109 silly get   { date: 'Mon, 13 Apr 2015 22:50:27 GMT',
109 silly get     server: 'Apache',
109 silly get     via: '1.1 varnish',
109 silly get     'last-modified': 'Mon, 13 Apr 2015 22:49:57 GMT',
109 silly get     'cache-control': 'max-age=60',
109 silly get     etag: '"5997G8NY1OJEMZ1HNHL7VBX5J"',
109 silly get     age: '39',
109 silly get     'x-served-by': 'cache-lax1429-LAX',
109 silly get     'x-cache': 'HIT',
109 silly get     'x-cache-hits': '3',
109 silly get     'x-timer': 'S1428965427.838696,VS0,VE0',
109 silly get     vary: 'Accept',
109 silly get     'content-length': '0',
109 silly get     'keep-alive': 'timeout=10, max=50',
109 silly get     connection: 'Keep-Alive' } ]
110 verbose etag https://registry.npmjs.org/bindings from cache
111 verbose get saving bindings to C:\Users\kumardi\AppData\Roaming\npm-cache\registry.npmjs.org\bindings\.cache.json
112 silly cache afterAdd bindings@1.0.0
113 verbose afterAdd C:\Users\kumardi\AppData\Roaming\npm-cache\bindings\1.0.0\package\package.json not in flight; writing
114 verbose afterAdd C:\Users\kumardi\AppData\Roaming\npm-cache\bindings\1.0.0\package\package.json written
115 silly install resolved [ { name: 'bindings',
115 silly install resolved     description: 'Helper module for loading your native module\'s .node file',
115 silly install resolved     keywords: [ 'native', 'addon', 'bindings', 'gyp', 'waf', 'c', 'c++' ],
115 silly install resolved     version: '1.0.0',
115 silly install resolved     author:
115 silly install resolved      { name: 'Nathan Rajlich',
115 silly install resolved        email: 'nathan@tootallnate.net',
115 silly install resolved        url: 'http://tootallnate.net' },
115 silly install resolved     repository:
115 silly install resolved      { type: 'git',
115 silly install resolved        url: 'git://github.com/TooTallNate/node-bindings.git' },
115 silly install resolved     main: './bindings.js',
115 silly install resolved     _id: 'bindings@1.0.0',
115 silly install resolved     dist:
115 silly install resolved      { shasum: 'c3ccde60e9de6807c6f1aa4ef4843af29191c828',
115 silly install resolved        tarball: 'http://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz' },
115 silly install resolved     maintainers: [ [Object], [Object] ],
115 silly install resolved     directories: {},
115 silly install resolved     _shasum: 'c3ccde60e9de6807c6f1aa4ef4843af29191c828',
115 silly install resolved     _resolved: 'https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz',
115 silly install resolved     _from: 'bindings@1.0.0',
115 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-bindings/issues' },
115 silly install resolved     readme: 'ERROR: No README data found!',
115 silly install resolved     homepage: 'https://github.com/TooTallNate/node-bindings' } ]
116 info install bindings@1.0.0 into C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
117 info installOne bindings@1.0.0
118 verbose installOne of bindings to C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt not in flight; installing
119 verbose lock using C:\Users\kumardi\AppData\Roaming\npm-cache\_locks\bindings-df22862bde6f88ac.lock for C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
120 silly install write writing bindings 1.0.0 to C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
121 silly cache addNamed cb bindings@1.0.0
122 verbose unbuild node_modules\bcrypt\node_modules\bindings
123 verbose gentlyRm vacuuming C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
124 verbose tar unpack C:\Users\kumardi\AppData\Roaming\npm-cache\bindings\1.0.0\package.tgz
125 verbose tar unpacking to C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
126 verbose gentlyRm vacuuming C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
127 silly gunzTarPerm modes [ '777', '666' ]
128 silly gunzTarPerm extractEntry package.json
129 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
130 silly gunzTarPerm extractEntry README.md
131 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
132 silly gunzTarPerm extractEntry bindings.js
133 silly gunzTarPerm modified mode [ 'bindings.js', 420, 438 ]
134 info preinstall bindings@1.0.0
135 silly install resolved []
136 verbose about to build C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
137 info build C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
138 verbose linkStuff [ false,
138 verbose linkStuff   false,
138 verbose linkStuff   false,
138 verbose linkStuff   'C:\\Projects\\Launch Pad\\Instrumentation App\\Rigel\\Rigel\\node_modules\\bcrypt\\node_modules' ]
139 info linkStuff bindings@1.0.0
140 verbose linkBins bindings@1.0.0
141 verbose linkMans bindings@1.0.0
142 verbose rebuildBundles bindings@1.0.0
143 info install bindings@1.0.0
144 info postinstall bindings@1.0.0
145 verbose unlock done using C:\Users\kumardi\AppData\Roaming\npm-cache\_locks\bindings-df22862bde6f88ac.lock for C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt\node_modules\bindings
146 verbose about to build C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
147 info build C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
148 verbose linkStuff [ false,
148 verbose linkStuff   false,
148 verbose linkStuff   false,
148 verbose linkStuff   'C:\\Projects\\Launch Pad\\Instrumentation App\\Rigel\\Rigel\\node_modules' ]
149 info linkStuff bcrypt@0.7.8
150 verbose linkBins bcrypt@0.7.8
151 verbose linkMans bcrypt@0.7.8
152 verbose rebuildBundles bcrypt@0.7.8
153 verbose rebuildBundles [ 'bindings' ]
154 info install bcrypt@0.7.8
155 verbose unsafe-perm in lifecycle true
156 info bcrypt@0.7.8 Failed to exec install script
157 verbose unlock done using C:\Users\kumardi\AppData\Roaming\npm-cache\_locks\bcrypt-e5466765c32f258e.lock for C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
158 verbose stack Error: bcrypt@0.7.8 install: `node-gyp rebuild`
158 verbose stack Exit status 1
158 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
158 verbose stack     at EventEmitter.emit (events.js:110:17)
158 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
158 verbose stack     at ChildProcess.emit (events.js:110:17)
158 verbose stack     at maybeClose (child_process.js:1008:16)
158 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
159 verbose pkgid bcrypt@0.7.8
160 verbose cwd C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel
161 error Windows_NT 6.1.7601
162 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
163 error node v0.12.0
164 error npm  v2.5.1
165 error code ELIFECYCLE
166 error bcrypt@0.7.8 install: `node-gyp rebuild`
166 error Exit status 1
167 error Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
167 error This is most likely a problem with the bcrypt package,
167 error not with npm itself.
167 error Tell the author that this fails on your system:
167 error     node-gyp rebuild
167 error You can get their info via:
167 error     npm owner ls bcrypt
167 error There is likely additional logging output above.
168 verbose exit [ 1, true ]
169 verbose unbuild node_modules\bcrypt
170 info preuninstall bcrypt@0.7.8
171 info uninstall bcrypt@0.7.8
172 verbose unbuild rmStuff bcrypt@0.7.8 from C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules
173 info postuninstall bcrypt@0.7.8
174 verbose gentlyRm vacuuming C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
175 silly gentlyRm purging C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules\bcrypt
176 silly gentlyRm quitting because other entries in C:\Projects\Launch Pad\Instrumentation App\Rigel\Rigel\node_modules

**Comment by Thunraz** [comment]
It looks like you're trying to install version 0.7.8 with node 0.12. As you can see in the README you need for version 0.11 or higher at least bcrypt version 0.8 or higher.
Try setting your bcrypt dependency in `package.json` to version "latest" and run `npm update bcrypt --save`. If you've got all the libraries installed bcrypt should compile just fine.

**Comment by DilipK01** [comment]
Thank you, Julian! I’ll try that.
I thought that running “npm install bcrypt” would install the latest version – regardless of whatever I may have in my package.json file.

Anyway, thanks again!

Dilip Kumar
