### ISSUE TITLE
Add salt argument to compare/compareSync

### ISSUE THREAD

**Issue by andrewjmead** [ncb000gt/node.bcrypt.js#295]
First, great library. Thanks.

I'm using a salt for my passwords and found it odd that when hashing my password there was an argument for the salt, but when comparing my passwords there is not. I was assuming the syntax would be something like:

```
var isMatch = bcrypt.hashSync(password, salt, hashedPassword);
```

Is this something you would consider doing or consider accepting a PR for?

**Comment by ncb000gt** [comment]
bcrypt salts are stored as a part of the hash and are therefore not required in the comparison as a separate parameter. :)
