### ISSUE TITLE
Unexpected Match

### ISSUE THREAD

**Issue by stankowalczyk** [ncb000gt/node.bcrypt.js#309]
Hi,

I'm generating a 256 character long token for users, and before storing it I hash and salt it. Now when comparing the token string to the hash and salt, I have been able to get a match if I enter in *255 characters* of the 256 character long token.

I couldn't find any information about a limitation to the amount of characters that I can hash, so I thought I'd better put in an issue.

Let me provide an example of what I mean when I say that I get a match on 255 out of the 256 characters. Lets say I generated the following token (I shortened it for readability):
`n1ijdASDiwdj1.....fdsjiofe12roij13FEF`,
I can then get a match with the above token if I provide 255 characters of it, that is one character missing. Examples of what I've been able to make a match with are below (again shortened for readability):
`n1ijdASDiwdj1.....fdsjiofe12roij13FE` (missing last character)
`1ijdASDiwdj1.....fdsjiofe12roij13FEF` (missing first character)
`n1ijdASDiwdj1.....fdsjiofe12roij1FEF` (missing interior character, fourth character from the end)

I have also tested with dramatically shorter strings (eg. 7 character and 28 characters long), and everything works as it should.

I'm using Node version `v0.10.37` (from Chris Lea's PPA), bcrypt version `0.8.3`, on Ubuntu 12.04.3 LTS.

Here is a snippet similar to how I create my token:
```
crypto = require('crypto');
length = 256;
token = crypto.randomBytes(Math.ceil(length * 3 / 4))
     .toString('base64')
     .slice(0, length)
     .replace(/\+/g, '0')
     .replace(/\//g, '0');
```

Here is how I am generating the salted / hashed version:
```
bcrypt = require('crypt');
salt = bcrypt.genSaltSync(10);
hash = bcrypt.hashSync(token, salt);
```

And here is how I'm doing my comparison:
```
bcrypt = require('crypt');
bcrypt.compareSync(candidateToken, token);
```

Thanks!

**Comment by defunctzombie** [comment]
There is a maximum length of 56 bytes of user input (maybe more?) See the User Input section of the [Bcrypt](http://en.wikipedia.org/wiki/Bcrypt) wikipedia article.

Basically, yes, this is expected and by design. Also no point in using so many characters today :)

**Comment by stankowalczyk** [comment]
Thank you for the quick reply :)
