### ISSUE TITLE
bcrypt 0.8.4 not working on Ubuntu

### ISSUE THREAD

**Issue by lrobson555** [ncb000gt/node.bcrypt.js#321]
Hi,

I'm running bcrypt 0.8.4 (also tried 0.8.3) with Node 0.10.40 and NPM 1.4.28 on Ubuntu 14.04.1 LTS, and I'm having issues getting bcrypt.compare to work.

The callback parameter compareResult (below) is just returning false, even though I know that the password is definitely correct, and err is coming back as null. No errors are thrown at all, not even on install.
Weirdly, is does work locally on OSX 10.10, running the same versions.

The issue is resolved, however, by reverting bcrypt back to 0.7.8. 

```
bcrypt.compare(password, user.password, function (err, compareResult) {
    if (!compareResult || err) {
        res.json(result);
        return;
    }
    /* .... */
});
```

**Comment by defunctzombie** [comment]
Probably something else in your code. Without a failing example unfortunately not much can be done.

**Comment by lrobson555** [comment]
Ok, I'll take another look at my code.
As I mentioned, it's strange that the latest version (0.8.4) works when I run it on my Mac, but not on the Ubuntu server. The Ubuntu server seems to only work correctly with bcrypt 0.7.8.
