### ISSUE TITLE
404 during installation

### ISSUE THREAD

**Issue by rbaprado** [ncb000gt/node.bcrypt.js#328]
I am running io.js under linux.

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.0.0/node-v3.0.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 4.1.5-1-ARCH
gyp ERR! command "/usr/bin/iojs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/buzz/Projetos/mobtag/backend/node_modules/bcrypt
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.1.5-1-ARCH
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "install" "bcrypt"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

**Comment by rbaprado** [comment]
Would you care to explain why?

**Comment by defunctzombie** [comment]
Has nothing to do with this module. Seems like npm error.

**Comment by rbaprado** [comment]
I would not judge that so quickly, since it only seems to happen with this
package, but nervermind...

Em qua, 19 de ago de 2015 às 11:00, Roman Shtylman <notifications@github.com>
escreveu:

> Has nothing to do with this module. Seems like npm error.
>

**Comment by defunctzombie** [comment]
```gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v3.0.0/node-v3.0.0.tar.gz``` is pretty clear and would have nothing to do with this package unless some dependency is wanting to download a newer node. I would check your env setup.

**Comment by rbaprado** [comment]
3.0.0 is version number known for io.js, not node. I guess some dependency
of bcrypt has some problem being hardcoded for nodejs or something like
that, anyway, that is blocking bcrypt installation, that is why I reported
that to you, since I cannot look into that right now, hence I am currently
using bcryptjs because of that.

Em qua, 19 de ago de 2015 às 11:37, Roman Shtylman <notifications@github.com>
escreveu:
