### ISSUE TITLE
Node 4.0 support

### ISSUE THREAD

**Issue by jedireza** [ncb000gt/node.bcrypt.js#334]
:pager: Let's support the latest and greatest

**Comment by jedireza** [comment]
FYI: Tests are passing on my mac using node v4.0, but are failing on Travis.

**Comment by DJMcK** [comment]
Tried to reproduce but [all seemed ok](https://travis-ci.org/DJMcK/node.bcrypt.js/jobs/79366188).

**Comment by jedireza** [comment]
That's good to hear. Maybe I'm mis-reading my log. In my project's travis build I'm seeing:

```bash
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
```

https://travis-ci.org/jedireza/frame/jobs/79366957

Maybe this is an issue with `node-gyp` actually. If so, apologies for the bad report.

We could still use this issue to track updating the README for supported versions.

**Comment by defunctzombie** [comment]
Should work fine on node v4 since it works on iojs v3. Make sure to clear away any old cache for npm or build files and rebuild. Also make sure your environment is in order.

**Comment by tresdin** [comment]
I got a similar error while I was trying to install bcrypt on node v4.0.
