### ISSUE TITLE
Cannot install on my system

### ISSUE THREAD

**Issue by Oreqizer** [ncb000gt/node.bcrypt.js#336]
I got this following error:

![err](https://cloud.githubusercontent.com/assets/11172408/9815082/b4079784-5893-11e5-9f17-09f548e31796.png)

It said to contact the author of bcrypt, so I am doing exactly that.

**Comment by defunctzombie** [comment]
please provide a full text based error log to the node-gyp project. I can't tell what other errors there are but it seems they are related to building with the v8 headers and not this project.

For future reference screenshots like this are pretty useless compared to a text log file which can be searched.

**Comment by Oreqizer** [comment]
Hi, sorry for me being so brief back then, was in a hurry and kind of upset (Windows really gives you a bad time when installing node-gyp).

Anyway, I uninstalled VS2012 and installed 2015 version, all works fine now.

**Comment by nullivex** [comment]
@defunctzombie Okay, been scanning around.

I have Visual Studio Express 2013 and getting a similar failure. I am going to see if upgrading to 2015 helps. If it does maybe we should make a note about this on the README to stop from the bugs getting opened up left and right.

@Oreqizer Thank you, this is the only information I have seen leading towards a fix.

**Comment by defunctzombie** [comment]
@nullivex If that is the case then the instructions here (https://github.com/nodejs/node-gyp) should be updated. Our readme simply says that you need the pre-reqs for node-gyp on your platform and we link to this readme. Once you confirm your findings, opening an issue on the node-gyp repo (or even a PR for the readme) would be appreciated I am sure.
