### ISSUE TITLE
Update nan version

### ISSUE THREAD

**Issue by AdriVanHoudt** [ncb000gt/node.bcrypt.js#342]
Not sure what changed but according to https://github.com/nodejs/node/issues/2798#issuecomment-139301141 you should use nan > 2.0.7
Just thought to give you a heads up

**Comment by defunctzombie** [comment]
works fine on node v4. If you have a specific issue please describe it.

**Comment by AdriVanHoudt** [comment]
nope not really just saw it passing by while reading the issue on the node repo and thought to notify ^^

**Comment by kylehotchkiss** [comment]
Gonna have to +1 this, I'm having a difficult time with NaN not compiling on travis (thousands of lines of compiler issues), and it looks like NaN has some commits post 2.0.9 relating to node.js 4.0.0 compatibility:

<img width="578" alt="screen shot 2015-09-16 at 1 21 42 pm" src="https://cloud.githubusercontent.com/assets/108172/9912513/fc8ca1da-5c75-11e5-9557-b89695d97a2d.png">

**Comment by gabeio** [comment]
It's strange, Travis is spewing errors about errors relating to nan & bcrypt, but when I build it on a local ubuntu it works fine... I can't get travis fixed though so all my builds between iojs 3.0 - node 4.x have/are completely broken (I have tried clearing travis cache).

**Comment by defunctzombie** [comment]
Have you looked the our Travis config file to see the extra things we added
to make v4 work? It doesn't work just by adding a new version to the list,
you have to update gcc.

**Comment by gabeio** [comment]
ah no I have not.

**Comment by gabeio** [comment]
@defunctzombie thank you so much that fixed it! :clap:
