### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 14. in nodejs v4.1.0

### ISSUE THREAD

**Issue by alfredobarron** [ncb000gt/node.bcrypt.js#347]
/Users/abarron/Documents/projects/api/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/abarron/Documents/projects/api/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/abarron/Documents/projects/api/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/abarron/Documents/projects/api/api/services/EncryptService.js:1:76)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by TooTallNate** [comment]
You need to re-compile the bcrypt module, in order to get a matching module version.

**Comment by alfredobarron** [comment]
Thanks @TooTallNate but my problem was npm version.

**Comment by rt2zz** [comment]
@alfredobarron can you explain what you mean by your problem was 'npm version'? I am having the same issue.

**Comment by alfredobarron** [comment]
@rt2zz when updated npm to version 3.3.3 fired error, I returned to version 2.14.3 and solved that problem.

**Comment by rt2zz** [comment]
Ok I see. In my case I was mixed up on which version of node I was running. Everything is working for me now, using npm 3.3.3

**Comment by alfredobarron** [comment]
my version of node is 4.1.0 which you use? how to solved that problem? to update the version npm 3.3.3

**Comment by rt2zz** [comment]
I am on node 4.1.1 and npm 3.3.3

I was confused on node/modules versions, but once I upgraded node/npm and run `npm install bcrypt` the problem was resolved.

**Comment by alfredobarron** [comment]
@rt2zz Thanks!

**Comment by rt2zz** [comment]
and just to be clear, the version of bcrypt installed is `0.8.5`

**Comment by learner1024** [comment]
I had same issue. I have mint linux with node 4.1.1 installed in /usr/bin. This is how I solved it - I used [TJ's npm package "n"](https://github.com/tj/n) - which I had already installed globally with another copy of node with version 0.12.6 in /user/local/somewhere. earlier I was using following when same issue was spotted
```javascript
nodejs init.js
```
with above mentioned packaged I used following to solve my problem.
```javascript
n use 0.12.6 init.js
```

```

**Comment by siawyoung** [comment]
Can confirm that reinstalling bcrypt works. I ran into this while switching between Node versions using n.

**Comment by SargTeX** [comment]
This does not work for me. I reinstalled bcrypt now for a dozen times, but it didn't fix a thing.

npm -v: 3.7.1
nodejs -v: 5.6.0

I've tried `npm uninstall bcrypt` && `npm install bcrypt` as well as removing the modules by hand & reinstalling them, as well as `npm remove bcrypt`.

Could you give a more detailed explanation on how "rebuilding"/"reinstallation" should fix this?

**Comment by buunguyen** [comment]
Have the same problem with NPM 3. Hope this will be reopened and fixed. Meanwhile, switching to a [pure-JS implementation](https://www.npmjs.com/package/bcryptjs).

**Comment by ecordani** [comment]
Same problem, resolved with a simple `uninstall`-`install` (v.0.8.5).
Node v.4.2.6
Npm v.2.14.12

**Comment by grdunn** [comment]
Same issue, however `uninstall` and `install` solved by issue. Same as @ecordani

**Comment by venkat-imaginea** [comment]
Ufff... Upgrading Node and Npm resolved the issue.. This seriously sucked the juice out of me..

Solution:
Node: 5.6.0
Npm: 3.6.0

**Comment by anorudes** [comment]
@buunguyen. Thanks, you helped me a lot ) bcryptjs is very fine )

**Comment by leomperes** [comment]
My problem was solved deleting the whole `node_modules` folder and install everything again with `$ npm install`.

**Comment by Hmachalani** [comment]
@leomperes that worked for me too!
