### ISSUE TITLE
when attempting to specify a salt with $2b$ bcrypt throws an error

### ISSUE THREAD

**Issue by craigxgibbons** [ncb000gt/node.bcrypt.js#349]
According to the [Bcrypt page on Wikipedia](https://en.wikipedia.org/wiki/Bcrypt), $2a$, $2b$ and $2y$ are all valid.

**Comment by defunctzombie** [comment]
iirc the 2a ab 2b are deprecated. This library only supports the 2y prefix.

**Comment by craigxgibbons** [comment]
Looking at the code it seems the library only supports the 2a prefix.
https://github.com/ncb000gt/node.bcrypt.js/blob/master/src/bcrypt.cc#L136

I did find some reference to 2y being the one to go for going forward but there are still plenty of 2a & 2b around, I think it would still be of value to support those for my 2c.

**Comment by defunctzombie** [comment]
If you make a PR I would review but otherwise this is unlikely to happen.
Most users of the library won't care.

**Comment by craigxgibbons** [comment]
Ok fair enough, I'm not a C developer but I'll try put something together. Thanks

**Comment by diversario** [comment]
All hashes generated with this library are $2a prefixed as far as I can tell.

**Comment by diversario** [comment]
```
➜ npm ls bcrypt
└── bcrypt@0.8.5
➜ node
> var b = require('bcrypt')
undefined
> b.hashSync('123', b.genSaltSync())
'$2a$10$vC.XMbLbIA1XqaD2E9pyK.GWjrs7MikKni3jYMgFt10Qzd.8vay/K'
```

So, am I using it wrong? Is it supposed to generate `$2y` hashes?

**Comment by julien-f** [comment]
Same here, I am getting `$2a$` prefixes instead of `$2y`.

@defunctzombie Is it normal?

**Comment by defunctzombie** [comment]
Take a look at this issue: https://github.com/ncb000gt/node.bcrypt.js/issues/175

**Comment by julien-f** [comment]
Thank you.
