### ISSUE TITLE
Keep getting same issues

### ISSUE THREAD

**Issue by Binnsler** [ncb000gt/node.bcrypt.js#350]
I've got a Node app hosted on Heroku that started throwing errors and won't allow me to push updates to Heroku:

> bcrypt@0.8.5 install /tmp/build_698ac324646fd7bf7b3f23c91e08d929/node_modules/bcrypt
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_698ac324646fd7bf7b3f23c91e08d929/node_modules/bcrypt/build'
remote:          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
remote:          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
remote:          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
remote:        In file included from ../src/bcrypt_node.cc:1:0:
remote:        ../node_modules/nan/nan.h:140:53: fatal error: nan_callbacks.h: No such file or directory
remote:         #include "nan_callbacks.h"  // NOLINT(build/include)
remote:                                                             ^
remote:        compilation terminated.
remote:        make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
remote:        make: Leaving directory `/tmp/build_698ac324646fd7bf7b3f23c91e08d929/node_modules/bcrypt/build'
remote:        gyp ERR! build error 
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_698ac324646fd7bf7b3f23c91e08d929/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
remote:        gyp ERR! stack     at emitTwo (events.js:87:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote:        gyp ERR! System Linux 3.13.0-61-generic
remote:        gyp ERR! command "/tmp/build_698ac324646fd7bf7b3f23c91e08d929/.heroku/node/bin/node" "/tmp/build_698ac324646fd7bf7b3f23c91e08d929/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_698ac324646fd7bf7b3f23c91e08d929/node_modules/bcrypt
remote:        gyp ERR! node -v v4.1.1
remote:        gyp ERR! node-gyp -v v3.0.3
remote:        gyp ERR! not ok 
remote:        
remote:        npm ERR! Linux 3.13.0-61-generic
remote:        npm ERR! argv "/tmp/build_698ac324646fd7bf7b3f23c91e08d929/.heroku/node/bin/node" "/tmp/build_698ac324646fd7bf7b3f23c91e08d929/.heroku/node/bin/npm" "rebuild"
remote:        npm ERR! node v4.1.1
remote:        npm ERR! npm  v2.14.4
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the bcrypt package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls bcrypt
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_698ac324646fd7bf7b3f23c91e08d929/npm-debug.log
remote: 
remote: -----> Build failed

I wasn't editing anything in relation to bcrypt, nor did I do anything with it. The error is coming from this app:
https://github.com/Binnsler/TheOfficialGalacticCollective

**Comment by gblock0** [comment]
:+1: I am getting the same error with node on heroku.

````
 make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
remote:        make: Leaving directory `/tmp/build_1ce713e91911e1a748c7190632896f4c/node_modules/lwip/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_1ce713e91911e1a748c7190632896f4c/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
remote:        gyp ERR! stack     at emitTwo (events.js:87:13)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote:        gyp ERR! System Linux 3.13.0-57-generic
remote:        gyp ERR! command "/tmp/build_1ce713e91911e1a748c7190632896f4c/.heroku/node/bin/node" "/tmp/build_1ce713e91911e1a748c7190632896f4c/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_1ce713e91911e1a748c7190632896f4c/node_modules/lwip
remote:        gyp ERR! node -v v4.1.1
remote:        gyp ERR! node-gyp -v v3.0.3
remote:        gyp ERR! not ok
remote:        npm ERR! Linux 3.13.0-57-generic
remote:        npm ERR! argv "/tmp/build_1ce713e91911e1a748c7190632896f4c/.heroku/node/bin/node" "/tmp/build_1ce713e91911e1a748c7190632896f4c/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_1ce713e91911e1a748c7190632896f4c/.npmrc"
remote:        npm ERR! node v4.1.1
remote:        npm ERR! npm  v2.14.4
remote:        npm ERR! code ELIFECYCLE
remote:
remote:        npm ERR! bcrypt@0.8.0 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the bcrypt@0.8.0 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the bcrypt package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls bcrypt
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_1ce713e91911e1a748c7190632896f4c/npm-debug.log
````

I tried logging onto the heroku box and running npm install -g node-gyp, but that didn't help. 

On my heroku box:
`node -v` : `v0.12.7`
`npm -v` : `2.11.3`

I am also trying to install bcrypt 0.8.0.

Please let me know if you need anything else from me.

**Comment by Binnsler** [comment]
Nothing I did was able to get it fixed, so I ended up switching to bcryptjs:

https://www.npmjs.com/package/bcryptjs

It was built entirely off of bcrypt and uses exactly the same methods, so literally all you have to do is change your requirement from var bcrypt = require('bcrypt');     to      var bcrypt = require('bcryptjs');

Here is it in my package.json:
"bcryptjs": "^2.3.0"

That's all I did and boom, my app was right back up, plus Heroku push updates go a lot faster.

**Comment by gblock0** [comment]
@Binnsler, this worked for bcrypt now I'm getting the same error with lwip :(. I think this has to do with Node v4 not being fully supported by all these modules. Thanks for your help though!

**Comment by gblock0** [comment]
@Binnsler I added:

```
```

**Comment by defunctzombie** [comment]
I am running an app on heroku node v4 with bcrypt no problem.
