### ISSUE TITLE
npm install bcrypt fails in install: node-gyp rebuild

### ISSUE THREAD

**Issue by AndresHernandezl** [ncb000gt/node.bcrypt.js#351]
I am using Debian and I have this error, someone who can help me;

npm install --save  bcrypt
|
> bcrypt@0.8.5 install /home/tronwares/Escritorio/Oglit/Provedores-App/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tronwares/Escritorio/Oglit/Provedores-App/node_modules/bcrypt
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "bcrypt"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tronwares/Escritorio/Oglit/Provedores-App/npm-debug.log

**Comment by willmcclellan** [comment]
If you are on OSX make sure you have updated Xcode from the App Store. See #330

**Comment by Jiran** [comment]
I am also having this issue and I have updated Xcode and the command line tools from the App Store. When I try to deploy my Node App to heroku, I am getting the same issue running on linux

**Comment by jrthib** [comment]
I'm having this issue as well. Haven't been able to figure it out why.

**Comment by Jiran** [comment]
@AndresHernandezl & @jrthib if you are on Heroku, just use the official buildpack for it to compile properly. If on Linux you may need to use a C++11-capable compiler: g++ 4.8 or newer, or clang++ 3.4 or newer. based on the [issue here](https://github.com/nodejs/node-gyp/issues/742#issuecomment-143101591)

**Comment by AndresHernandezl** [comment]
I met my mistake , with the installation of a package on my Debian 8 operating system :

sudo apt- get install build-essential

Then install bcrypt:

npm install bcrypt

**Comment by wayjake** [comment]
Thank you!!! @AndresHernandezl

**Comment by madcurie** [comment]
thank you @AndresHernandezl

**Comment by leduykhanhhedspi** [comment]
thank you !!! @AndresHernandezl

**Comment by dicksonchellakon** [comment]
Thank You @AndresHernandezl

**Comment by WojtylaCZ** [comment]
Same issue, solved by solution from @AndresHernandezl Thank you!

**Comment by michellaevens** [comment]
Same issue here with Bcrypt on Debian. Thank you @AndresHernandezl

**Comment by alexcvcoelho** [comment]
Thank you @AndresHernandezl , success on Linux Mint
