### ISSUE TITLE
Build error with Node v4.0.0

### ISSUE THREAD

**Issue by Voffkaa** [ncb000gt/node.bcrypt.js#356]
After updating to node v4.0.0 build error occured:

gyp: /usr/lib64/node_modules/npm/node_modules/node-gyp/addon-rpm.gypi not found (cwd: /mnt/Data/Projects/MailAgency/node_modules/bcrypt) while reading includes of binding.gyp while trying to load binding.gyp

gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:358:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.7-24-desktop
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/Data/Projects/MailAgency/node_modules/bcrypt
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Linux 3.16.7-24-desktop
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "bcrypt"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

**Comment by Voffkaa** [comment]
Added same report to
https://bugzilla.opensuse.org/show_bug.cgi?id=948733

**Comment by fwertz** [comment]
I'm sensing a little bit of irritation on the README for reporting bugs. NodeJS bcrypt will not build using `Node v4.0.0`. That version is [stable](https://nodejs.org/en/blog/release/v4.0.0/). Since `node-gyp` 

> only works with stable/released versions of node

and

> the `bcrypt` module uses node-gyp to build and install you'll need a stable version of node to use bcrypt

I'm not following how this issue is closable. I don't see a duplicate open right now, so that can't be it.

**Comment by kennysmoothx** [comment]
+ 1 Same issue on Heroku
