### ISSUE TITLE
npm install bcrypt fails on Node 4.0  RH 6 with gcc 4.8.5  

### ISSUE THREAD

**Issue by smartmouse** [ncb000gt/node.bcrypt.js#362]
[io@winlnx3e test]$ npm install bcrypt
\
> bcrypt@0.8.5 install /home/io/test/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/io/test/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /home/io/gcc/include/c++/4.8.5/bits/move.h:57:0,
                 from /home/io/gcc/include/c++/4.8.5/bits/stl_pair.h:59,
                 from /home/io/gcc/include/c++/4.8.5/utility:70,
                 from /home/io/gcc/include/c++/4.8.5/algorithm:60,
                 from ../node_modules/nan/nan.h:28,
                 from ../src/bcrypt_node.cc:1:
/home/io/gcc/include/c++/4.8.5/type_traits:236:41: error: template argument 1 is invalid
     struct __is_integral_helper<__int128>
                                         ^
/home/io/gcc/include/c++/4.8.5/type_traits:240:50: error: template argument 1 is invalid
     struct __is_integral_helper<unsigned __int128>
                                                  ^
/home/io/gcc/include/c++/4.8.5/type_traits:1487:36: error: template argument 1 is invalid
     struct __make_unsigned<__int128>
                                    ^
/home/io/gcc/include/c++/4.8.5/type_traits:1569:43: error: template argument 1 is invalid
     struct __make_signed<unsigned __int128>
                                           ^
In file included from /home/io/gcc/include/c++/4.8.5/bits/stl_algo.h:59:0,
                 from /home/io/gcc/include/c++/4.8.5/algorithm:62,
                 from ../node_modules/nan/nan.h:28,
                 from ../src/bcrypt_node.cc:1:
/home/io/gcc/include/c++/4.8.5/cstdlib:178:10: error: expected unqualified-id before ‘__int128’
   inline __int128
          ^
In file included from /home/io/gcc/include/c++/4.8.5/random:43:0,
                 from /home/io/gcc/include/c++/4.8.5/bits/stl_algo.h:65,
                 from /home/io/gcc/include/c++/4.8.5/algorithm:62,
                 from ../node_modules/nan/nan.h:28,
                 from ../src/bcrypt_node.cc:1:
/home/io/gcc/include/c++/4.8.5/limits:1405:35: error: template argument 1 is invalid
     struct numeric_limits<__int128>
                                   ^
/home/io/gcc/include/c++/4.8.5/limits:1479:44: error: template argument 1 is invalid
     struct numeric_limits<unsigned __int128>
                                            ^
In file included from /home/io/gcc/include/c++/4.8.5/random:50:0,
                 from /home/io/gcc/include/c++/4.8.5/bits/stl_algo.h:65,
                 from /home/io/gcc/include/c++/4.8.5/algorithm:62,
                 from ../node_modules/nan/nan.h:28,
                 from ../src/bcrypt_node.cc:1:
/home/io/gcc/include/c++/4.8.5/bits/random.h:106:26: error: expected unqualified-id before ‘__int128’
       { typedef unsigned __int128 type; };
                          ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/io/test/node_modules/bcrypt/build'
gyp ERR! build error
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

**Comment by nmccready** [comment]
Why is this closed without a comment?
