### ISSUE TITLE
bcrypt install fails on openshift platform

### ISSUE THREAD

**Issue by sorokh** [ncb000gt/node.bcrypt.js#370]
I'm running into a snag on openshift with this bcrypt module.
Running a custom node on openshift with the lates nodejs package as you can see in the log below.
I' trying to run an npm install -g bcrypt and I get compilation issues on the platform:

+ npm install -g bcrypt
> bcrypt@0.8.5 install /var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/lib/node_modules/bcrypt
> node-gyp rebuild

gyp WARN EACCES user "55faa53a89f5cf4d87000215" does not have permission to access the dev dir "/var/lib/openshift/55faa53a89f5cf4d87000215/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
make: Entering directory `/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/lib/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /tmp/.node-gyp/5.0.0/include/node/node.h:42,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/bcrypt_node.cc:1:
/tmp/.node-gyp/5.0.0/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/tmp/.node-gyp/5.0.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: At global scope:
/tmp/.node-gyp/5.0.0/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/tmp/.node-gyp/5.0.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:794: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:819: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:831: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: At global scope:
/tmp/.node-gyp/5.0.0/include/node/v8.h:856: error: expected unqualified-id before ‘using’
/tmp/.node-gyp/5.0.0/include/node/v8.h:1093: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h:1099: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:3204: error: ‘nullptr’ was not declared in this scope
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:7154: error: ‘nullptr’ was not declared in this scope
In file included from ../node_modules/nan/nan.h:184,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../node_modules/nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:65: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:70: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:77: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:84: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:92: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:99: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:119: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:126: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:131: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:136: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:140: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:146: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:151: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:163: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:169: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:175: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:195: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:206: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:214: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
In file included from ../node_modules/nan/nan.h:189,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_converters.h:14: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../node_modules/nan/nan_converters.h:14: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:16: error: ISO C++ forbids declaration of ‘Maybe’ with no type
../node_modules/nan/nan_converters.h:16: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:26: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:27: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:28: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:29: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:30: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:31: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:32: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:42: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:43: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:44: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:45: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:46: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_converters.h:59,
                 from ../node_modules/nan/nan.h:189,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_converters_43_inl.h:18: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:19: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Number>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:20: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::String>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:21: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Object>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:22: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Integer>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:23: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:24: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Int32>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:34: error: ‘return_t’ in class ‘Nan::imp::ToFactory<bool>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:35: error: ‘return_t’ in class ‘Nan::imp::ToFactory<double>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:36: error: ‘return_t’ in class ‘Nan::imp::ToFactory<long int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:37: error: ‘return_t’ in class ‘Nan::imp::ToFactory<unsigned int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:38: error: ‘return_t’ in class ‘Nan::imp::ToFactory<int>’ does not name a type
In file included from ../node_modules/nan/nan.h:190,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../node_modules/nan/nan_new.h:21: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../node_modules/nan/nan_new.h:28: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../node_modules/nan/nan_new.h:35: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: At global scope:
../node_modules/nan/nan_new.h:43: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../node_modules/nan/nan_new.h:43: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_new.h:75: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:141: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:147: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:148: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:160: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:161: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:162: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:163: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:165: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:166: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:182: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:183: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_new.h:189,
                 from ../node_modules/nan/nan.h:190,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_implementation_12_inl.h:56: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Date>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:209: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:228: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:234: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:266: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:274: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:280: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:287: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:293: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:298: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:359: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:366: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../node_modules/nan/nan.h:190,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_new.h:291: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:297: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:303: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:309: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:315: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:321: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:327: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../node_modules/nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../node_modules/nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../node_modules/nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../node_modules/nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../node_modules/nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../node_modules/nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../node_modules/nan/nan.h:644: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../node_modules/nan/nan.h:644: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../node_modules/nan/nan.h:645: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../node_modules/nan/nan.h:645: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:653: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:675: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:691: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:704: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:721: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:727: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:735: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:742: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:748: error: expected initializer before ‘<’ token
/tmp/.node-gyp/5.0.0/include/node/v8.h: In member function ‘void Nan::Callback::SetFunction(const v8::Local<v8::Function>&)’:
/tmp/.node-gyp/5.0.0/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../node_modules/nan/nan.h:1368: error:   in call to ‘Set’
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1490: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../node_modules/nan/nan.h:1508: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:1542: error: no matching function for call to ‘New(const char*)’
../node_modules/nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1832: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1845: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
In file included from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:2116: error: no matching function for call to ‘New(const char*&)’
/tmp/.node-gyp/5.0.0/include/node/v8.h:3019: error: argument dependent lookup finds ‘class v8::Set’
../node_modules/nan/nan.h:2117: error:   in call to ‘Set’
../node_modules/nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:2124: error: no matching function for call to ‘To(v8::Local<v8::Value>&)’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../node_modules/nan/nan.h:2137: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../node_modules/nan/nan.h:2143: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/lib/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.34.1.el6.x86_64
gyp ERR! command "/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/bin/node" "/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/lib/node_modules/bcrypt
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.34.1.el6.x86_64
npm ERR! argv "/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/bin/node" "/var/lib/openshift/55faa53a89f5cf4d87000215/app-root/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/latest_nodejs/node-v5.0.0-linux-x64/bin/npm" "install" "-g" "bcrypt"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

any hints on this issue?

**Comment by defunctzombie** [comment]
environment config/setup. make sure you have the correct versions of the compilers, etc and read the dependency requirements for node-gyp

**Comment by sorokh** [comment]
Ok,
you can markdown this issue. 
According to the following discussion http://stackoverflow.com/questions/33532528/nodejs-4-5-npm-install-fail-for-bcrypt-and-db-migrate  it would be related to an outdated gcc version on the platform.

As I wasn't able to upgrading gcc, downgrading node to 0.12.7 solved the issue.
