### ISSUE TITLE
bcrypt always fails.. no clue why.

### ISSUE THREAD

**Issue by inselmensch** [ncb000gt/node.bcrypt.js#374]
hey guys,

i'm running into those errors which i can not solve by myself, anyone got an idea of how i could install my projects with bcrypt (without, everything works fine obviously)?

Using Ubuntu.

log i've got:

    > bcrypt@0.8.5 install /var/www/awesome-project/node_modules/bcrypt
    > node-gyp rebuild

    child_process: customFds option is deprecated, use stdio instead.
    make: Entering directory `/var/www/awesome-projects/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
    In file included from ../src/bcrypt_node.cc:1:0:
    ../node_modules/nan/nan.h: In function ‘void Nan::SetCounterFunction(v8::CounterLookupCallback)’:
    ../node_modules/nan/nan.h:449:32: error: ‘class v8::Isolate’ has no member named ‘SetCounterFunction’
         v8::Isolate::GetCurrent()->SetCounterFunction(cb);
                                    ^
    ../node_modules/nan/nan.h: In function ‘void Nan::SetCreateHistogramFunction(v8::CreateHistogramCallback)’:
    ../node_modules/nan/nan.h:454:32: error: ‘class v8::Isolate’ has no member named ‘SetCreateHistogramFunction’
         v8::Isolate::GetCurrent()->SetCreateHistogramFunction(cb);
                                    ^
    ../node_modules/nan/nan.h: In function ‘void Nan::SetAddHistogramSampleFunction(v8::AddHistogramSampleCallback)’:
    ../node_modules/nan/nan.h:459:32: error: ‘class v8::Isolate’ has no member named ‘SetAddHistogramSampleFunction’
         v8::Isolate::GetCurrent()->SetAddHistogramSampleFunction(cb);
                                    ^
    ../node_modules/nan/nan.h: In function ‘bool Nan::IdleNotification(int)’:
    ../node_modules/nan/nan.h:470:39: error: ‘class v8::Isolate’ has no member named ‘IdleNotification’
         return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                           ^
    ../node_modules/nan/nan.h: In function ‘void Nan::LowMemoryNotification()’:
    ../node_modules/nan/nan.h:475:32: error: ‘class v8::Isolate’ has no member named ‘LowMemoryNotification’
         v8::Isolate::GetCurrent()->LowMemoryNotification();
                                    ^
    ../node_modules/nan/nan.h: In function ‘void Nan::ContextDisposedNotification()’:
    ../node_modules/nan/nan.h:479:32: error: ‘class v8::Isolate’ has no member named ‘ContextDisposedNotification’
         v8::Isolate::GetCurrent()->ContextDisposedNotification();
                                    ^
    make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
    make: Leaving directory `/var/www/awesome-projects/node_modules/bcrypt/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
    gyp ERR! System Linux 3.13.0-24-generic
    gyp ERR! command "node" "/root/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /var/www/awesome-project/node_modules/bcrypt
    ERR! node -v v0.11.14
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    -
    > kerberos@0.0.17 install /var/www/awesome-project/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
    > (node-gyp rebuild) || (exit 0)

    child_process: customFds option is deprecated, use stdio instead.
    make: Entering directory `/var/www/awesome-project/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    In file included from ../lib/kerberos.cc:1:0:
    ../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
     #include <gssapi/gssapi.h>
                               ^
    compilation terminated.
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
    make: Leaving directory `/var/www/awesome-project/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
    gyp ERR! System Linux 3.13.0-24-generic
    gyp ERR! command "node" "/root/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /var/www/awesome-projects/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
    gyp ERR! node -v v0.11.14
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Linux 3.13.0-24-generic
    npm ERR! argv "node" "/root/.nvm/v0.11.14/bin/npm" "install" "--production"
    npm ERR! node v0.11.14
    npm ERR! npm  v2.1.2
    npm ERR! code ELIFECYCLE

    npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the bcrypt@0.8.5 install script.
    npm ERR! This is most likely a problem with the bcrypt package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls bcrypt
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /var/www/awesome-projects/npm-debug.log

**Comment by JimmyLv** [comment]
got the same error, T^T

**Comment by kelukelu** [comment]
I'v got the same issue on OSX El Capitan and Node 0.10.38

**Comment by inselmensch** [comment]
just tried to install node-gyp to use command `node-gyp rebuild` but it didn't work. something's maybe broken? don't know, what to switch to if no one got a clue what happens here. :-/

**Comment by inselmensch** [comment]
is there no solution to this error? it's hard to debug.

**Comment by krispy1298** [comment]
Works on non-el capitan macs. Used one to email myself a production version module folder.

**Comment by defunctzombie** [comment]
node -v v0.11.14

Use a stable released version of node
