### ISSUE TITLE
Error: version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

### ISSUE THREAD

**Issue by slavafomin** [ncb000gt/node.bcrypt.js#376]
Hello!

Thank you for this great module.

I've encountered an issue with it today after deploying new version of my application to the production server. Functionality related to bcrypt is not working and I'm getting the following errors in the console: 

```
node /var/www/app.js: relocation error: /var/www/node_modules/bcrypt/build/Release/bcrypt_lib.node: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

```
$ cat /etc/issue
Ubuntu 14.04.3 LTS \n \l
```

```
$ uname -a
Linux vdc4558 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ node --version
v5.1.0
```

My production app is broken and I can't find a way to make it work again, please advise ASAP if possible. Thank you very much! Will try to revert for now.

I've tried to update `libstdc++6`, but with no luck:

```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
sudo apt-get install libstdc++6
```

**Comment by baslr** [comment]
did u tried on the target server
```
rm -rf node_modules
npm install
```

**Comment by defunctzombie** [comment]
sounds like an issue with your environment/setup. Best to get support via a better support forum as issues here would be related to code/functionality of this specific module and not your environment or other setup problems.
