### ISSUE TITLE
Cannot Install Bcrypt

### ISSUE THREAD

**Issue by StephenMayeux** [ncb000gt/node.bcrypt.js#378]
### Context
1.  NodeJS 5.1.0
2.  npm 3.4.1
3.  Make, GCC, Python 2.7, OpenSSL and node-gyp installed
  * Python env variable is pointing to python2.7
4. Please read err below:

> bcrypt@0.8.5 install /home/stephen/Node Udemy/comevents/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/stephen/Node Udemy/comevents/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
/home/stephen/Node Udemy/comevents/node_modules/.bin/touch: 1: /home/stephen/Node Udemy/comevents/node_modules/.bin/touch: Syntax error: "(" unexpected
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 2
make: Leaving directory `/home/stephen/Node Udemy/comevents/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-33-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stephen/Node Udemy/comevents/node_modules/bcrypt
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "bcrypt"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stephen/Node Udemy/comevents/npm-debug.log

**Comment by StephenMayeux** [comment]
After digging in, I concluded it was my environment. Issue resolved.

**Comment by ivanst-stoyanov** [comment]
@StephenMayeux can you elaborate on what was the problem with your environment? I am experiencing the same issue.

**Comment by StephenMayeux** [comment]
@ivanst-stoyanov I'm afraid I don't remember. I wrote my issue two months ago, and it might have been an issue with my Python installation. If you think Python has been installed correctly on your machine, you might want to try ```sudo npm install bcrypt -g```.
