### ISSUE TITLE
Issues instaling on Windows 7 with Node 0.10.41

### ISSUE THREAD

**Issue by rperlas** [ncb000gt/node.bcrypt.js#381]
I get the following error messages when attempting to install Windows 7 with Node 0.10.41:

$ npm install bcrypt
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.

bcrypt@0.8.5 install C:\Users\IBM_ADMIN\Desktop\node_modules\bcrypt
node-gyp rebuild

C:\Users\IBM_ADMIN\Desktop\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 527, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 503, in gyp_main
    options.circular_check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1867, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 402, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2015'
gyp
npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! cwd C:\Users\IBM_ADMIN\Desktop
npm ERR! node -v v0.10.41
npm ERR! npm -v 1.4.29
npm ERR! code ELIFECYCLE
npm

**Comment by smartmouse** [comment]
I upgraded NPM to the latest version and  install bcrypt , got more information about the issue.

C:\Users\IBM_ADMIN>npm -v
3.5.1

C:\Users\IBM_ADMIN>cd testbrcypt
The system cannot find the path specified.

C:\Users\IBM_ADMIN>mkdir testbcrypt
A subdirectory or file testbcrypt already exists.

C:\Users\IBM_ADMIN>cd testbcrypt

C:\Users\IBM_ADMIN\testbcrypt>npm install bcrypt

> bcrypt@0.8.5 install C:\Users\IBM_ADMIN\node_modules\bcrypt
> node-gyp rebuild


C:\Users\IBM_ADMIN\node_modules\bcrypt>if not defined npm_config_node_gyp (node
"C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Stu
dio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_m
odules\npm\node_modules\node-gyp\lib\build.js:128:23)
gyp ERR! stack     at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\no
de_modules\node-gyp\lib\build.js:110:11
gyp ERR! stack     at F (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm
\node_modules\which\which.js:78:16)
gyp ERR! stack     at E (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm
\node_modules\which\which.js:82:29)
gyp ERR! stack     at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\npm\no
de_modules\which\which.js:93:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modul
es\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IBM_ADMIN\node_modules\bcrypt
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.2.0
gyp ERR! not ok
npm WARN enoent ENOENT, open 'C:\Users\IBM_ADMIN\package.json'
npm WARN IBM_ADMIN No description
npm WARN IBM_ADMIN No repository field.
npm WARN IBM_ADMIN No README data
npm WARN IBM_ADMIN No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm\\node_modules\
\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! node v0.10.40
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!

It seems that node-gyp requires an older version of visual c++   and I do not have it.
I have updated my environment to have the latest visual studio c++ 2015.
