### ISSUE TITLE
Install fails on Ubuntu

### ISSUE THREAD

**Issue by aray12** [ncb000gt/node.bcrypt.js#384]
I am trying to get up and running with Vagrant and I have been experiencing problems install bcrypt v0.8.5 on the Ubuntu guest I am running. Up until this point I have been developing on OSX with no problems. When I run `npm install` it takes a really long time to install and then just outputs `Killed` at some point. So I ran `npm install --verbose` and this is what I get at the end before it just seems to hang:
```
make: Entering directory `/vagrant/node_modules/bcrypt/build'
  g++ '-DNODE_GYP_MODULE_NAME=bcrypt_lib' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/vagrant/.node-gyp/4.2.3/include/node -I/home/vagrant/.node-gyp/4.2.3/src -I/home/vagrant/.node-gyp/4.2.3/deps/uv/include -I/home/vagrant/.node-gyp/4.2.3/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw  -c -o Release/obj.target/bcrypt_lib/src/blowfish.o ../src/blowfish.cc
  g++ '-DNODE_GYP_MODULE_NAME=bcrypt_lib' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/vagrant/.node-gyp/4.2.3/include/node -I/home/vagrant/.node-gyp/4.2.3/src -I/home/vagrant/.node-gyp/4.2.3/deps/uv/include -I/home/vagrant/.node-gyp/4.2.3/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt.o.d.raw  -c -o Release/obj.target/bcrypt_lib/src/bcrypt.o ../src/bcrypt.cc
  g++ '-DNODE_GYP_MODULE_NAME=bcrypt_lib' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/vagrant/.node-gyp/4.2.3/include/node -I/home/vagrant/.node-gyp/4.2.3/src -I/home/vagrant/.node-gyp/4.2.3/deps/uv/include -I/home/vagrant/.node-gyp/4.2.3/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt_node.o.d.raw  -c -o Release/obj.target/bcrypt_lib/src/bcrypt_node.o ../src/bcrypt_node.cc
/
Killed
vagrant@vagrant-ubuntu-trusty-64:/vagrant$   g++ -shared -pthread -rdynamic -m64  -Wl,-soname=bcrypt_lib.node -o Release/obj.target/bcrypt_lib.node -Wl,--start-group Release/obj.target/bcrypt_lib/src/blowfish.o Release/obj.target/bcrypt_lib/src/bcrypt.o Release/obj.target/bcrypt_lib/src/bcrypt_node.o -Wl,--end-group 
  rm -rf "Release/bcrypt_lib.node" && cp -af "Release/obj.target/bcrypt_lib.node" "Release/bcrypt_lib.node"
make: Leaving directory `/vagrant/node_modules/bcrypt/build'
gyp info ok 
```
at which point it just stops outputting anything and hangs

I am using `node v4.2.3` and `npm v2.14.7`

I have done some searching on similar issues which have pointed to dependencies on python so my provisioning scripts runs `sudo apt-get -y install build-essential python2.7`. I also had trouble with a missing c++ compiler so my provisioning also runs `sudo apt-get -y install build-essential g++`. I also found [this](https://github.com/ncb000gt/node.bcrypt.js/issues/90) issue and tried `sudo npm i -g node-gyp && node-gyp clean` to no avail. 

Any guidance would be greatly appreciated. This is the last thing I need to fix before my dev environment is completely portable.

**Comment by defunctzombie** [comment]
Sounds like you are running out of memory in the VM. Just a hunch based on the `Killed` log line. I suggest trying on stackoverflow for more hands on help if increasing memory doesn't fix it. This is most certainly an issue localized to your environment and not a package issue.

**Comment by aray12** [comment]
@defunctzombie that was the problem. I appreciate the help
