### ISSUE TITLE
Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by arturojain** [ncb000gt/node.bcrypt.js#385]
[npm-debug.txt](https://github.com/ncb000gt/node.bcrypt.js/files/68832/npm-debug.txt)

**Comment by githubmann** [comment]
I have the same problem

**Comment by defunctzombie** [comment]
Updated to a newer version of bcrypt.

Also, would really help if you made issues that actually described what debugging you have tried and if you have tried to fix it.
