### ISSUE TITLE
Problem Issue!

### ISSUE THREAD

**Issue by Dariush-Tasdighi** [ncb000gt/node.bcrypt.js#396]
I do not know why! but when I wrote the below codes in my computer (Windows 10 64BIT), each time that I run my app, the result of hash of (for example: 1234512345) are not the same! please help me or fix it asap:

var bcrypt = require('bcrypt-nodejs');

bcrypt.hash('1234512345', null, null, function (err, hash) {

    console.log('HASH of 1234512345 is: ' + hash);

});

**Comment by defunctzombie** [comment]
Please read the readme on how to use this module.
