### ISSUE TITLE
npm bcrypt.js install problem

### ISSUE THREAD

**Issue by ghaddon1** [ncb000gt/node.bcrypt.js#409]
I get the following error when installing bcrypt.js.

bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.

Running Node v5.10.0
NPM 3.8.3

Thanks,
Gary

**Comment by conor909** [comment]
@defunctzombie Can you link to the resolved issue before closing, I can't find the issue with useful info.
