### ISSUE TITLE
Bcrypt installation issue with azure

### ISSUE THREAD

**Issue by Anshdesire** [ncb000gt/node.bcrypt.js#434]
Trying to get bcrypt on Azure api-apps

Getting this error
```
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.29\\node.exe" "D:\\Program Files (x86)\\npm\\1.4.10\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"
npm ERR! cwd D:\home\site\wwwroot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.10
npm ERR! code ELIFECYCLE
```

NPM - 1.4.10

**Comment by Anshdesire** [comment]
No reply ?? At least you should text here if this one is not an issue or something like that.

**Comment by defunctzombie** [comment]
Did you read the issue template?

**Comment by jamesdixon** [comment]
@Anshdesire how did you resolve this?

**Comment by chprasad** [comment]
@Anshdesire I am seeing the same error. Can you specify the resolution you found?

**Comment by jamesdixon** [comment]
@chprasad are you developing on windows?

**Comment by chprasad** [comment]
Found the resolution at http://stackoverflow.com/questions/38149603/npm-install-fails-with-error-c2373-with-vs2015-update-3. Global npm install is pulling in a older version of gyp. Updating the package.json for global npm to pull in node-gyp 3.4.0 and doing a subsequent npm install in the global npm install folder resolved the problem for me.

@jamesdixon I am using a windows server on azure for web test automation using selenium.
