### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by Flowdeeps** [ncb000gt/node.bcrypt.js#436]
* Searched existing issues (even closed ones) for your same problem

Have tried deleting the ~/.node-gyp folder as suggested in only similar issue to no avail.
* Make sure you have installed the required dependencies listed on the readme

Dependencies met.
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Have checked.

* What went wrong?

npm install bcrypt fails
* What did you expect to happen?

Expected it to pass and install
* Which version of nodejs and OS?

Node v: 4.4.0 Mac OS 10.11.5
* If you find a bug, please write a failing test.

NPM Log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'bcrypt' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose install initial load of /Users/me/Sites/Bandstats/Bandstats/package.json
5 warn package.json node_bandstats@0.0.0 No description
6 warn package.json node_bandstats@0.0.0 license should be a valid SPDX license expression
7 warn package.json node_bandstats@0.0.0 No bin file found at collect_facebook.js
8 verbose readDependencies loading dependencies from /Users/me/Sites/Bandstats/Bandstats/package.json
9 silly cache add args [ 'bcrypt@~0.7.4', null ]
10 verbose cache add spec bcrypt@~0.7.4
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'bcrypt@~0.7.4',
11 silly cache add   scope: null,
11 silly cache add   name: 'bcrypt',
11 silly cache add   rawSpec: '~0.7.4',
11 silly cache add   spec: '>=0.7.4 <0.8.0',
11 silly cache add   type: 'range' }
12 silly addNamed bcrypt@>=0.7.4 <0.8.0
13 verbose addNamed ">=0.7.4 <0.8.0" is a valid semver range for bcrypt
14 silly addNameRange { name: 'bcrypt', range: '>=0.7.4 <0.8.0', hasData: false }
15 silly mapToRegistry name bcrypt
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/bcrypt
19 verbose addNameRange registry:https://registry.npmjs.org/bcrypt not in flight; fetching
20 verbose request uri https://registry.npmjs.org/bcrypt
21 verbose request no auth needed
22 info attempt registry request try #1 at 3:18:42 PM
23 verbose request id 33e9f0b99276e647
24 verbose etag "2VUYIPMRT8KEG0NE3MENVNAOP"
25 http request GET https://registry.npmjs.org/bcrypt
26 http 304 https://registry.npmjs.org/bcrypt
27 verbose headers { date: 'Tue, 12 Jul 2016 14:18:44 GMT',
27 verbose headers   via: '1.1 varnish',
27 verbose headers   'cache-control': 'max-age=300',
27 verbose headers   etag: '"2VUYIPMRT8KEG0NE3MENVNAOP"',
27 verbose headers   age: '220',
27 verbose headers   connection: 'keep-alive',
27 verbose headers   'x-served-by': 'cache-lhr6327-LHR',
27 verbose headers   'x-cache': 'HIT',
27 verbose headers   'x-cache-hits': '2',
27 verbose headers   'x-timer': 'S1468333124.605084,VS0,VE0',
27 verbose headers   vary: 'Accept-Encoding' }
28 silly get cb [ 304,
28 silly get   { date: 'Tue, 12 Jul 2016 14:18:44 GMT',
28 silly get     via: '1.1 varnish',
28 silly get     'cache-control': 'max-age=300',
28 silly get     etag: '"2VUYIPMRT8KEG0NE3MENVNAOP"',
28 silly get     age: '220',
28 silly get     connection: 'keep-alive',
28 silly get     'x-served-by': 'cache-lhr6327-LHR',
28 silly get     'x-cache': 'HIT',
28 silly get     'x-cache-hits': '2',
28 silly get     'x-timer': 'S1468333124.605084,VS0,VE0',
28 silly get     vary: 'Accept-Encoding' } ]
29 verbose etag https://registry.npmjs.org/bcrypt from cache
30 verbose get saving bcrypt to /Users/me/.npm/registry.npmjs.org/bcrypt/.cache.json
31 verbose correctMkdir /Users/me/.npm correctMkdir not in flight; initializing
32 silly addNameRange number 2 { name: 'bcrypt', range: '>=0.7.4 <0.8.0', hasData: true }
33 silly addNameRange versions [ 'bcrypt',
33 silly addNameRange   [ '0.1.2',
33 silly addNameRange     '0.2.0',
33 silly addNameRange     '0.2.1',
33 silly addNameRange     '0.1.3',
33 silly addNameRange     '0.2.2',
33 silly addNameRange     '0.2.3',
33 silly addNameRange     '0.2.4',
33 silly addNameRange     '0.3.0',
33 silly addNameRange     '0.3.1',
33 silly addNameRange     '0.3.2',
33 silly addNameRange     '0.4.0',
33 silly addNameRange     '0.4.1',
33 silly addNameRange     '0.5.0',
33 silly addNameRange     '0.6.0',
33 silly addNameRange     '0.7.0',
33 silly addNameRange     '0.7.1',
33 silly addNameRange     '0.7.2',
33 silly addNameRange     '0.7.3',
33 silly addNameRange     '0.7.4',
33 silly addNameRange     '0.7.5',
33 silly addNameRange     '0.7.6',
33 silly addNameRange     '0.7.7',
33 silly addNameRange     '0.7.8',
33 silly addNameRange     '0.8.0',
33 silly addNameRange     '0.8.1',
33 silly addNameRange     '0.8.2',
33 silly addNameRange     '0.8.3',
33 silly addNameRange     '0.8.4',
33 silly addNameRange     '0.8.5',
33 silly addNameRange     '0.8.6',
33 silly addNameRange     '0.8.7' ] ]
34 silly addNamed bcrypt@0.7.8
35 verbose addNamed "0.7.8" is a plain semver version for bcrypt
36 silly cache afterAdd bcrypt@0.7.8
37 verbose afterAdd /Users/me/.npm/bcrypt/0.7.8/package/package.json not in flight; writing
38 verbose correctMkdir /Users/me/.npm correctMkdir not in flight; initializing
39 verbose afterAdd /Users/me/.npm/bcrypt/0.7.8/package/package.json written
40 silly install resolved [ { name: 'bcrypt',
40 silly install resolved     description: 'A bcrypt library for NodeJS.',
40 silly install resolved     keywords:
40 silly install resolved      [ 'bcrypt',
40 silly install resolved        'password',
40 silly install resolved        'auth',
40 silly install resolved        'authentication',
40 silly install resolved        'encryption',
40 silly install resolved        'crypt',
40 silly install resolved        'crypto' ],
40 silly install resolved     main: './bcrypt',
40 silly install resolved     version: '0.7.8',
40 silly install resolved     author: { name: 'Nick Campbell', url: 'https://github.com/ncb000gt' },
40 silly install resolved     engines: { node: '>= 0.6.0' },
40 silly install resolved     repository:
40 silly install resolved      { type: 'git',
40 silly install resolved        url: 'git+https://github.com/ncb000gt/node.bcrypt.js.git' },
40 silly install resolved     licenses: [ [Object] ],
40 silly install resolved     bugs: { url: 'https://github.com/ncb000gt/node.bcrypt.js/issues' },
40 silly install resolved     scripts:
40 silly install resolved      { test: 'node-gyp configure build && nodeunit test',
40 silly install resolved        install: 'node-gyp rebuild' },
40 silly install resolved     dependencies: { bindings: '1.0.0' },
40 silly install resolved     devDependencies: { nodeunit: '>=0.6.4' },
40 silly install resolved     contributors:
40 silly install resolved      [ [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object],
40 silly install resolved        [Object] ],
40 silly install resolved     gypfile: true,
40 silly install resolved     homepage: 'https://github.com/ncb000gt/node.bcrypt.js',
40 silly install resolved     _id: 'bcrypt@0.7.8',
40 silly install resolved     dist:
40 silly install resolved      { shasum: '42c99aac202918e947b5bd086110184f62745e3e',
40 silly install resolved        tarball: 'https://registry.npmjs.org/bcrypt/-/bcrypt-0.7.8.tgz' },
40 silly install resolved     _from: 'bcrypt@>=0.7.4 <0.8.0',
40 silly install resolved     _npmVersion: '1.4.6',
40 silly install resolved     _npmUser: { name: 'shtylman', email: 'shtylman@gmail.com' },
40 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
40 silly install resolved     directories: {},
40 silly install resolved     _shasum: '42c99aac202918e947b5bd086110184f62745e3e',
40 silly install resolved     _resolved: 'https://registry.npmjs.org/bcrypt/-/bcrypt-0.7.8.tgz',
40 silly install resolved     readme: 'ERROR: No README data found!' } ]
41 info install bcrypt@0.7.8 into /Users/me/Sites/Bandstats/Bandstats
42 info installOne bcrypt@0.7.8
43 verbose installOne of bcrypt to /Users/me/Sites/Bandstats/Bandstats not in flight; installing
44 verbose correctMkdir /Users/me/.npm/_locks correctMkdir not in flight; initializing
45 verbose lock using /Users/me/.npm/_locks/bcrypt-8047762cdc16dbfb.lock for /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
46 silly install write writing bcrypt 0.7.8 to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
47 verbose unbuild node_modules/bcrypt
48 silly gentlyRm /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt is being purged from base /Users/me/Sites/Bandstats/Bandstats
49 verbose gentlyRm don't care about contents; nuking /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
50 verbose tar unpack /Users/me/.npm/bcrypt/0.7.8/package.tgz
51 verbose tar unpacking to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
52 silly gentlyRm /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt is being purged
53 verbose gentlyRm don't care about contents; nuking /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
54 silly gunzTarPerm modes [ '755', '644' ]
55 silly gunzTarPerm extractEntry package.json
56 silly gunzTarPerm extractEntry .npmignore
57 silly gunzTarPerm extractEntry README.md
58 silly gunzTarPerm extractEntry LICENSE
59 silly gunzTarPerm extractEntry bcrypt.js
60 silly gunzTarPerm extractEntry Makefile
61 silly gunzTarPerm extractEntry .travis.yml
62 silly gunzTarPerm extractEntry binding.gyp
63 silly gunzTarPerm extractEntry examples/async_compare.js
64 silly gunzTarPerm extractEntry examples/forever_gen_salt.js
65 silly gunzTarPerm extractEntry CHANGELOG
66 silly gunzTarPerm extractEntry src/bcrypt.cc
67 silly gunzTarPerm extractEntry src/bcrypt_node.cc
68 silly gunzTarPerm extractEntry src/blowfish.cc
69 silly gunzTarPerm extractEntry src/node_blf.h
70 silly gunzTarPerm extractEntry test/async.js
71 silly gunzTarPerm extractEntry test/repetitions.js
72 silly gunzTarPerm extractEntry test/sync.js
73 verbose write writing to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/package.json
74 info preinstall bcrypt@0.7.8
75 verbose readDependencies loading dependencies from /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/package.json
76 silly prepareForInstallMany adding bindings@1.0.0 from bcrypt dependencies
77 verbose readDependencies loading dependencies from /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/package.json
78 silly cache add args [ 'bindings@1.0.0', null ]
79 verbose cache add spec bindings@1.0.0
80 silly cache add parsed spec Result {
80 silly cache add   raw: 'bindings@1.0.0',
80 silly cache add   scope: null,
80 silly cache add   name: 'bindings',
80 silly cache add   rawSpec: '1.0.0',
80 silly cache add   spec: '1.0.0',
80 silly cache add   type: 'version' }
81 silly addNamed bindings@1.0.0
82 verbose addNamed "1.0.0" is a plain semver version for bindings
83 silly mapToRegistry name bindings
84 silly mapToRegistry using default registry
85 silly mapToRegistry registry https://registry.npmjs.org/
86 silly mapToRegistry uri https://registry.npmjs.org/bindings
87 verbose addNameVersion registry:https://registry.npmjs.org/bindings not in flight; fetching
88 verbose request uri https://registry.npmjs.org/bindings
89 verbose request no auth needed
90 info attempt registry request try #1 at 3:18:43 PM
91 verbose etag "33TX4J3DNTGF7K41ZUV6OA182"
92 http request GET https://registry.npmjs.org/bindings
93 http 304 https://registry.npmjs.org/bindings
94 verbose headers { date: 'Tue, 12 Jul 2016 14:18:45 GMT',
94 verbose headers   via: '1.1 varnish',
94 verbose headers   'cache-control': 'max-age=300',
94 verbose headers   etag: '"33TX4J3DNTGF7K41ZUV6OA182"',
94 verbose headers   age: '183',
94 verbose headers   connection: 'keep-alive',
94 verbose headers   'x-served-by': 'cache-lhr6341-LHR',
94 verbose headers   'x-cache': 'HIT',
94 verbose headers   'x-cache-hits': '1',
94 verbose headers   'x-timer': 'S1468333125.660771,VS0,VE0',
94 verbose headers   vary: 'Accept-Encoding' }
95 silly get cb [ 304,
95 silly get   { date: 'Tue, 12 Jul 2016 14:18:45 GMT',
95 silly get     via: '1.1 varnish',
95 silly get     'cache-control': 'max-age=300',
95 silly get     etag: '"33TX4J3DNTGF7K41ZUV6OA182"',
95 silly get     age: '183',
95 silly get     connection: 'keep-alive',
95 silly get     'x-served-by': 'cache-lhr6341-LHR',
95 silly get     'x-cache': 'HIT',
95 silly get     'x-cache-hits': '1',
95 silly get     'x-timer': 'S1468333125.660771,VS0,VE0',
95 silly get     vary: 'Accept-Encoding' } ]
96 verbose etag https://registry.npmjs.org/bindings from cache
97 verbose get saving bindings to /Users/me/.npm/registry.npmjs.org/bindings/.cache.json
98 verbose correctMkdir /Users/me/.npm correctMkdir not in flight; initializing
99 silly cache afterAdd bindings@1.0.0
100 verbose afterAdd /Users/me/.npm/bindings/1.0.0/package/package.json not in flight; writing
101 verbose correctMkdir /Users/me/.npm correctMkdir not in flight; initializing
102 verbose afterAdd /Users/me/.npm/bindings/1.0.0/package/package.json written
103 silly install resolved [ { name: 'bindings',
103 silly install resolved     description: 'Helper module for loading your native module\'s .node file',
103 silly install resolved     keywords: [ 'native', 'addon', 'bindings', 'gyp', 'waf', 'c', 'c++' ],
103 silly install resolved     version: '1.0.0',
103 silly install resolved     author:
103 silly install resolved      { name: 'Nathan Rajlich',
103 silly install resolved        email: 'nathan@tootallnate.net',
103 silly install resolved        url: 'http://tootallnate.net' },
103 silly install resolved     repository:
103 silly install resolved      { type: 'git',
103 silly install resolved        url: 'git://github.com/TooTallNate/node-bindings.git' },
103 silly install resolved     main: './bindings.js',
103 silly install resolved     _id: 'bindings@1.0.0',
103 silly install resolved     dist:
103 silly install resolved      { shasum: 'c3ccde60e9de6807c6f1aa4ef4843af29191c828',
103 silly install resolved        tarball: 'https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz' },
103 silly install resolved     maintainers: [ [Object], [Object] ],
103 silly install resolved     directories: {},
103 silly install resolved     _shasum: 'c3ccde60e9de6807c6f1aa4ef4843af29191c828',
103 silly install resolved     _resolved: 'https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz',
103 silly install resolved     _from: 'bindings@1.0.0',
103 silly install resolved     bugs: { url: 'https://github.com/TooTallNate/node-bindings/issues' },
103 silly install resolved     readme: 'ERROR: No README data found!',
103 silly install resolved     homepage: 'https://github.com/TooTallNate/node-bindings#readme' } ]
104 info install bindings@1.0.0 into /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
105 info installOne bindings@1.0.0
106 verbose installOne of bindings to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt not in flight; installing
107 verbose correctMkdir /Users/me/.npm/_locks correctMkdir not in flight; initializing
108 verbose lock using /Users/me/.npm/_locks/bindings-ea010e3e9321b8cf.lock for /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
109 silly install write writing bindings 1.0.0 to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
110 verbose unbuild node_modules/bcrypt/node_modules/bindings
111 silly gentlyRm /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings is being purged from base /Users/me/Sites/Bandstats/Bandstats
112 verbose gentlyRm don't care about contents; nuking /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
113 verbose tar unpack /Users/me/.npm/bindings/1.0.0/package.tgz
114 verbose tar unpacking to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
115 silly gentlyRm /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings is being purged
116 verbose gentlyRm don't care about contents; nuking /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
117 silly gunzTarPerm modes [ '755', '644' ]
118 silly gunzTarPerm extractEntry package.json
119 silly gunzTarPerm extractEntry README.md
120 silly gunzTarPerm extractEntry bindings.js
121 verbose write writing to /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings/package.json
122 info preinstall bindings@1.0.0
123 verbose readDependencies loading dependencies from /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings/package.json
124 verbose readDependencies loading dependencies from /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings/package.json
125 silly install resolved []
126 verbose about to build /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
127 info build /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
128 info linkStuff bindings@1.0.0
129 silly linkStuff bindings@1.0.0 has /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules as its parent node_modules
130 verbose linkBins bindings@1.0.0
131 verbose linkMans bindings@1.0.0
132 verbose rebuildBundles bindings@1.0.0
133 info install bindings@1.0.0
134 info postinstall bindings@1.0.0
135 verbose unlock done using /Users/me/.npm/_locks/bindings-ea010e3e9321b8cf.lock for /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt/node_modules/bindings
136 verbose about to build /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
137 info build /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
138 info linkStuff bcrypt@0.7.8
139 silly linkStuff bcrypt@0.7.8 has /Users/me/Sites/Bandstats/Bandstats/node_modules as its parent node_modules
140 verbose linkBins bcrypt@0.7.8
141 verbose linkMans bcrypt@0.7.8
142 verbose rebuildBundles bcrypt@0.7.8
143 verbose rebuildBundles [ 'bindings' ]
144 info install bcrypt@0.7.8
145 verbose unsafe-perm in lifecycle true
146 info bcrypt@0.7.8 Failed to exec install script
147 verbose unlock done using /Users/me/.npm/_locks/bcrypt-8047762cdc16dbfb.lock for /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
148 verbose stack Error: bcrypt@0.7.8 install: `node-gyp rebuild`
148 verbose stack Exit status 1
148 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
148 verbose stack     at emitTwo (events.js:87:13)
148 verbose stack     at EventEmitter.emit (events.js:172:7)
148 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
148 verbose stack     at emitTwo (events.js:87:13)
148 verbose stack     at ChildProcess.emit (events.js:172:7)
148 verbose stack     at maybeClose (internal/child_process.js:827:16)
148 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
149 verbose pkgid bcrypt@0.7.8
150 verbose cwd /Users/me/Sites/Bandstats/Bandstats
151 error Darwin 15.5.0
152 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bcrypt"
153 error node v4.4.0
154 error npm  v2.14.20
155 error code ELIFECYCLE
156 error bcrypt@0.7.8 install: `node-gyp rebuild`
156 error Exit status 1
157 error Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
157 error This is most likely a problem with the bcrypt package,
157 error not with npm itself.
157 error Tell the author that this fails on your system:
157 error     node-gyp rebuild
157 error You can get information on how to open an issue for this project with:
157 error     npm bugs bcrypt
157 error Or if that isn't available, you can get their info via:
157 error
157 error     npm owner ls bcrypt
157 error There is likely additional logging output above.
158 verbose exit [ 1, true ]
159 verbose unbuild node_modules/bcrypt
160 info preuninstall bcrypt@0.7.8
161 info uninstall bcrypt@0.7.8
162 verbose unbuild rmStuff bcrypt@0.7.8 from /Users/me/Sites/Bandstats/Bandstats/node_modules
163 info postuninstall bcrypt@0.7.8
164 silly gentlyRm /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt is being purged from base /Users/me/Sites/Bandstats/Bandstats
165 verbose gentlyRm don't care about contents; nuking /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
166 silly vacuum-fs purging /Users/me/Sites/Bandstats/Bandstats/node_modules/bcrypt
167 silly vacuum-fs removing /Users/me/Sites/Bandstats/Bandstats/node_modules
168 silly vacuum-fs finished vacuuming up to /Users/me/Sites/Bandstats/Bandstats

**Comment by defunctzombie** [comment]
Bring this to the attention of the npm team. There is nothing in this log indicating what failed (command or otherwise) and as such makes me think the error is with npm and not this module.

**Comment by michael-merletti** [comment]
I have this error, and I dont find solution....
please help me...

/srv/data/web/vhosts/default/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /srv/data/web/vhosts/default/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/srv/data/web/vhosts/default/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/srv/data/web/vhosts/default/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/data/web/vhosts/default/server.js:76:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
