### ISSUE TITLE
Error while loading npm-bcrypt@0.8.7 

### ISSUE THREAD

**Issue by mzulkifel** [ncb000gt/node.bcrypt.js#439]
Error while loading npm-bcrypt@0.8.7 

C:\Users\Muhammad Zulkifel\WebstormProjects\Afroganix>meteor add accounts-passwo
rd
 => Errors while adding packages:

While loading package npm-bcrypt@0.8.7:
error: Command failed: C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32
\dev_bundle\bin\npm.cmd
rebuild --no-bin-links --update-binary
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files
(x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32
\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-
1w61yor\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-
1w61yor\npm-debug.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files
(x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32
\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild"
gyp ERR! cwd C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-
1w61yor\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Muhammad
Zulkifel\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows
.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Muhammad
Zulkifel\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-
1w61yor\npm-debug.log

**Comment by uzi547** [comment]
I have the same problem with bcrypt0.7.8_2

meteor add okland:accounts-phone

 => Errors while adding packages:

While loading package npm-bcrypt@0.7.8_2:
error: Command failed: C:\Users\WKUUSER\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild --no-bin-links --update-binary
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\WKUUSER\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\WKUUSER\AppData\Local\.meteor\packages\npm-bcrypt\0.7.8_2\npm\node_modules\.temp-48uis9\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\WKUUSER\AppData\Local\.meteor\packages\npm-bcrypt\0.7.8_2\npm\node_modules\.temp-48uis9\npm-debug.log
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\WKUUSER\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\WKUUSER\AppData\Local\.meteor\packages\npm-bcrypt\0.7.8_2\npm\node_modules\.temp-48uis9\node_modules\bcrypt
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\WKUUSER\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\WKUUSER\AppData\Local\.meteor\packages\npm-bcrypt\0.7.8_2\npm\node_modules\.temp-48uis9\npm-debug.log

**Comment by mzulkifel** [comment]
Git closed this issue , without resolving it .
