### ISSUE TITLE
npm install bcrypt -- fails 

### ISSUE THREAD

**Issue by IDCOLL** [ncb000gt/node.bcrypt.js#446]
Trying to update execute meteor npm install --save bcrypt as prompted by Meteor for native implementation.

Update fails however, even after I updated nodejs (v4.5.0) and performed NPM update as well. 
Using Windows 10.

Console indicates Python Env variable not set, but it is set. Executing Python from console works.

My log from my console shows the following (Attached NPM-DEBUG)
[npm-debug.docx](https://github.com/ncb000gt/node.bcrypt.js/files/467586/npm-debug.docx)
:

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\-----\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\python\python.exe", you can set the PYTHON

 env variable.
gyp ERR! stack     at failNoPython (C:\Users\-----\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\-----\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Users\\------\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\------\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\code\Test_Env\node_modules\bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\------\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Ian Collins\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.1_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "bcrypt"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\Test_Env\npm-debug.log

**Comment by defunctzombie** [comment]
make sure you have python installed in the location it is looking for it at (or do what it says and set the python environment variable. Please follow the instructions on our readme or the node-gyp readme for getting your environment setup properly
