### ISSUE TITLE
Cannot build under Windows 10

### ISSUE THREAD

**Issue by rbaprado** [ncb000gt/node.bcrypt.js#448]
It was not possible to build under Windows 10:
```
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': red
efinition; different type modifiers [D:\Buzz\Projetos\mobtag\backend\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
```
node-gyp is installed (I did npm install --global --production windows-build-tools as per node-gyp instructions).

```
node --version
v6.6.0
npm --version
3.10.3
```
[npm-debug.log.txt](https://github.com/ncb000gt/node.bcrypt.js/files/488209/npm-debug.log.txt)

**Comment by rbaprado** [comment]
Nevermind, upgrading npm to 3.10.8 solved the problem...

**Comment by HoverBaum** [comment]
Thanks for this... an entire day of trying all the things to find out I should just update npm ^^
